# Final Project

## Architectural Decision: Infrastructure & Security Compliance

### Context

The project requires a high-performance vector database to support hybrid search capabilities within a RAG (Retrieval-Augmented Generation) pipeline. While managed cloud solutions are available, modern enterprise standards increasingly mandate that sensitive data processing remains strictly within the organization's protected security perimeter.

### Decision

In light of these requirements, this project prioritizes the deployment of Qdrant as a locally hosted container (simulating deployment within a corporate internal infrastructure) rather than utilizing a managed cloud service.

### Rationale

**Data Sovereignty:** By keeping the vector store and the RAG retrieval process within the corporate network, we ensure that all sensitive data remains strictly within the company's information security perimeter.

**Regulatory Compliance:** This approach aligns with internal policies that prohibit the transmission of proprietary or sensitive data to third-party cloud environments. This is often a decisive factor for maintaining the integrity of the knowledge base and is a key consideration during software selection.

**Security Control:** Local deployment allows for direct oversight of access logs, network isolation, and encryption protocols in accordance with the security standards of most organizations.

## Dataset

### Dataset Selection Rationale

#### Context

To fully implement and validate the concepts covered in the Qdrant Essentials course, the ["Global News Dataset"](https://www.kaggle.com/datasets/everydaycodings/global-news-dataset) (available via Kaggle) was selected as the primary testing resource.

#### Selection Criteria

**Content Variability:** The dataset features a combination of concise news briefs and extensive long-form articles. This variety is essential for implementing and testing different chunking strategies, ensuring that the retrieval process effectively captures both the broad context and specific details.

**Hybrid Search Implementation:** The availability of rich metadata (author, publication, date) alongside extensive body text allows for a comprehensive implementation of Hybrid Search. This enables the combination of dense vector similarity with sparse vector retrieval and metadata filtering.

**RAG Pipeline Validation:** The scale and thematic breadth of the dataset provide an ideal environment for building a robust Retrieval-Augmented Generation (RAG) pipeline, where the quality of context retrieval is critical for the LLM’s performance.

**Performance Benchmarking:** The dataset size is sufficient to demonstrate Qdrant’s indexing efficiency and its ability to handle high-dimensional vector embeddings in a scenario that closely mimics real-world production environments.

Load the selected dataset:

In [21]:
from kagglehub import dataset_load, KaggleDatasetAdapter

dataset = dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "everydaycodings/global-news-dataset",
    "data.csv",
)

dataset.head(5)

,article_id,source_id,source_name,author,title,description,url,url_to_image,published_at,content,category,full_content
0,89541,NaN,International Business Times,Paavan MATHEMA,UN Chief Urges World To 'Stop The Madness' Of ...,UN Secretary-General Antonio Guterres urged th...,https://www.ibtimes.com/un-chief-urges-world-s...,https://d.ibtimes.com/en/full/4496078/nepals-g...,2023-10-30 10:12:35.000000,UN Secretary-General Antonio Guterres urged th...,Nepal,UN Secretary-General Antonio Guterres urged th...
1,89542,NaN,Prtimes.jp,NaN,RANDEBOOよりワンランク上の大人っぽさが漂うニットとベストが新登場。,[株式会社Ainer]\nRANDEBOO（ランデブー）では2023年7月18日(火)より公...,https://prtimes.jp/main/html/rd/p/000000147.00...,https://prtimes.jp/i/32220/147/ogp/d32220-147-...,2023-10-06 04:40:02.000000,"RANDEBOO2023718()WEB2023 Autumn Winter \n""Nepa...",Nepal,NaN
2,89543,NaN,VOA News,webdesk@voanews.com (Agence France-Presse),UN Chief Urges World to 'Stop the Madness' of ...,UN Secretary-General Antonio Guterres urged th...,https://www.voanews.com/a/un-chief-urges-world...,https://gdb.voanews.com/01000000-0a00-0242-60f...,2023-10-30 10:53:30.000000,"Kathmandu, Nepal UN Secretary-General Antonio...",Nepal,NaN
3,89545,NaN,The Indian Express,Editorial,Sikkim warning: Hydroelectricity push must be ...,Ecologists caution against the adverse effects...,https://indianexpress.com/article/opinion/edit...,https://images.indianexpress.com/2023/10/edit-...,2023-10-06 01:20:24.000000,At least 14 persons lost their lives and more ...,Nepal,At least 14 persons lost their lives and more ...
4,89547,NaN,The Times of Israel,Jacob Magid,"200 foreigners, dual nationals cut down in Ham...","France lost 35 citizens, Thailand 33, US 31, U...",https://www.timesofisrael.com/200-foreigners-d...,https://static.timesofisrael.com/www/uploads/2...,2023-10-27 01:08:34.000000,"Scores of foreign citizens were killed, taken ...",Nepal,NaN

### Dataset cleaning

In modern RAG (Retrieval-Augmented Generation) architectures, the quality of indexed data directly determines system accuracy. Thorough data cleaning and normalization address several critical challenges:
- **Improving Semantic Accuracy**: Embedding models are highly sensitive to noise. Removing redundant characters, tags, and formatting artifacts minimizes vector distortion, ensuring that document proximity in the latent space is based on meaning rather than formatting quirks.
- **Mitigating Hallucinations**: High-quality cleaning ensures reliable grounding for LLM responses. Excluding "garbage" data from the context allows the model to operate strictly on relevant facts.
- **Infrastructure Optimization**: Deduplication and the removal of redundant fields reduce the size of the vector index. This improves search latency and decreases storage costs within the Vector DB.
- **Filter Reliability**: Normalizing metadata (such as case folding and standardizing date formats like RFC 3339) ensures consistency when using hybrid search and hard filters.

Summary: An effective data preparation pipeline transforms a raw dataset into a structured knowledge base optimized for high-precision retrieval.

#### Preliminary dataset cleaning

The following fields have been selected as metadata:
- `source_name` — source title.
- `published_at` — publication date.
- `category` — news category.

The `title` field will be merged into `full_content`, as titles provide critical semantic context. The updated `full_content` field will serve as the primary source for vector search.
The `author` and `url_to_image` fields are discarded: the former contains significant noise, while the latter often points to unreachable resources.

In [22]:
import pandas as pd

dataset = dataset.drop(columns=['article_id', 'source_id', 'content', 'description', 'url_to_image', 'author'])

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30 10:12:35.000000,Nepal,UN Secretary-General Antonio Guterres urged th...
1,Prtimes.jp,RANDEBOOよりワンランク上の大人っぽさが漂うニットとベストが新登場。,https://prtimes.jp/main/html/rd/p/000000147.00...,2023-10-06 04:40:02.000000,Nepal,NaN
2,VOA News,UN Chief Urges World to 'Stop the Madness' of ...,https://www.voanews.com/a/un-chief-urges-world...,2023-10-30 10:53:30.000000,Nepal,NaN
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06 01:20:24.000000,Nepal,At least 14 persons lost their lives and more ...
4,The Times of Israel,"200 foreigners, dual nationals cut down in Ham...",https://www.timesofisrael.com/200-foreigners-d...,2023-10-27 01:08:34.000000,Nepal,NaN
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29 10:57:22,Home,Karnataka Deputy Chief Minister D K Shivakumar...
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29 08:41:18,Home,FC Barcelona have guaranteed at least $767.6 m...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29 10:01:12,Home,The photo from David and Sarah Lubarsky's wedd...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29 13:44:33,Home,Kerber’s Farm: Bringing Farm To Table To Manha...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29 14:00:00,Home,Cofounder at UpperKey. Passionate about proper...

Drop missing values from the dataset:

In [23]:
dataset = dataset.dropna(subset=['source_name', 'title', 'url', 'published_at', 'category', 'full_content'])

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30 10:12:35.000000,Nepal,UN Secretary-General Antonio Guterres urged th...
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06 01:20:24.000000,Nepal,At least 14 persons lost their lives and more ...
6,Al Jazeera English,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25 09:58:17.000000,Nepal,"India, the first non-Arab country to recognise..."
7,The Indian Express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02 05:48:58.000000,Nepal,Written by Alex Travelli and Hari Kumar No nat...
12,The Times of India,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02 01:12:47.000000,Nepal,NEW DELHI: India preferred Bangladesh over Nep...
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29 10:57:22,Home,Karnataka Deputy Chief Minister D K Shivakumar...
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29 08:41:18,Home,FC Barcelona have guaranteed at least $767.6 m...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29 10:01:12,Home,The photo from David and Sarah Lubarsky's wedd...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29 13:44:33,Home,Kerber’s Farm: Bringing Farm To Table To Manha...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29 14:00:00,Home,Cofounder at UpperKey. Passionate about proper...

Strip newlines and leading/trailing whitespace from all fields:

In [24]:
metadata_columns = ['source_name', 'title', 'category']

for col in metadata_columns:
    dataset[col] = dataset[col].str.replace(r'[\n\r]+', ' ', regex=True)
    dataset[col] = dataset[col].str.strip()

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30 10:12:35.000000,Nepal,UN Secretary-General Antonio Guterres urged th...
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06 01:20:24.000000,Nepal,At least 14 persons lost their lives and more ...
6,Al Jazeera English,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25 09:58:17.000000,Nepal,"India, the first non-Arab country to recognise..."
7,The Indian Express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02 05:48:58.000000,Nepal,Written by Alex Travelli and Hari Kumar No nat...
12,The Times of India,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02 01:12:47.000000,Nepal,NEW DELHI: India preferred Bangladesh over Nep...
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29 10:57:22,Home,Karnataka Deputy Chief Minister D K Shivakumar...
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29 08:41:18,Home,FC Barcelona have guaranteed at least $767.6 m...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29 10:01:12,Home,The photo from David and Sarah Lubarsky's wedd...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29 13:44:33,Home,Kerber’s Farm: Bringing Farm To Table To Manha...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29 14:00:00,Home,Cofounder at UpperKey. Passionate about proper...

Deduplicate rows:

In [25]:
dataset = dataset.drop_duplicates()

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30 10:12:35.000000,Nepal,UN Secretary-General Antonio Guterres urged th...
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06 01:20:24.000000,Nepal,At least 14 persons lost their lives and more ...
6,Al Jazeera English,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25 09:58:17.000000,Nepal,"India, the first non-Arab country to recognise..."
7,The Indian Express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02 05:48:58.000000,Nepal,Written by Alex Travelli and Hari Kumar No nat...
12,The Times of India,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02 01:12:47.000000,Nepal,NEW DELHI: India preferred Bangladesh over Nep...
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29 10:57:22,Home,Karnataka Deputy Chief Minister D K Shivakumar...
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29 08:41:18,Home,FC Barcelona have guaranteed at least $767.6 m...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29 10:01:12,Home,The photo from David and Sarah Lubarsky's wedd...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29 13:44:33,Home,Kerber’s Farm: Bringing Farm To Table To Manha...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29 14:00:00,Home,Cofounder at UpperKey. Passionate about proper...

#### Attribute `source_name`

In [26]:
for word in sorted(dataset['source_name'].unique()):
    print(word)

ABC News
Al Jazeera English
AllAfrica - Top Africa News
Android Central
BBC News
Boing Boing
Business Insider
CNA
CNN
Deadline
Digital Trends
ETF Daily News
Euronews
Forbes
Gizmodo.com
Globalsecurity.org
GlobeNewswire
International Business Times
Marketscreener.com
NPR
Phys.Org
RT
ReadWrite
The Indian Express
The Punch
The Times of India
The Verge
Time
Wired

No further issues in this field.

#### Attribute `category`

Targeted replacements to resolve inconsistencies within the same category:

In [27]:
dataset['category'] = dataset['category'].str.replace('America', 'United States', regex=False)

dataset['category'] = dataset['category'].str.replace('Congo, The Democratic Republic of the', 'Congo', regex=False)
dataset['category'] = dataset['category'].str.replace('Iran, Islamic Republic of', 'Iran', regex=False)
dataset['category'] = dataset['category'].str.replace('Korea, Republic of', 'Korea', regex=False)
dataset['category'] = dataset['category'].str.replace('Taiwan, Province of China', 'Taiwan', regex=False)
dataset['category'] = dataset['category'].str.replace('world', 'World', regex=False)

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30 10:12:35.000000,Nepal,UN Secretary-General Antonio Guterres urged th...
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06 01:20:24.000000,Nepal,At least 14 persons lost their lives and more ...
6,Al Jazeera English,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25 09:58:17.000000,Nepal,"India, the first non-Arab country to recognise..."
7,The Indian Express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02 05:48:58.000000,Nepal,Written by Alex Travelli and Hari Kumar No nat...
12,The Times of India,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02 01:12:47.000000,Nepal,NEW DELHI: India preferred Bangladesh over Nep...
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29 10:57:22,Home,Karnataka Deputy Chief Minister D K Shivakumar...
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29 08:41:18,Home,FC Barcelona have guaranteed at least $767.6 m...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29 10:01:12,Home,The photo from David and Sarah Lubarsky's wedd...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29 13:44:33,Home,Kerber’s Farm: Bringing Farm To Table To Manha...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29 14:00:00,Home,Cofounder at UpperKey. Passionate about proper...

Checking unique values:

In [28]:
for word in sorted(dataset['category'].unique()):
    print(word)

Afghanistan
Africa
Albania
Algeria
Amazon
Andorra
Angola
Anime
Antarctica
Architecture
Argentina
Armenia
Art
Artificial Intelligence
Aruba
Asia
Astronomy
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Beauty
Belarus
Belgium
Belize
Benin
Bermuda
Bhutan
Bitcoin
Blockchain
Bosnia and Herzegovina
Botswana
Brazil
Bulgaria
Burkina Faso
Burundi
COVID
Cabo Verde
Cambodia
Cameroon
Canada
Cars
Cayman Islands
Central African Republic
Chad
Chile
China
Christmas Island
Climate
Coding
Colombia
Congo
Costa Rica
Croatia
Cryptocurrency
Cuba
Cyprus
Côte d'Ivoire
DIY
Denmark
Design
Djibouti
Dominican Republic
Ecuador
Education
Egypt
El Salvador
Entrepreneurship
Eritrea
Estonia
Ethiopia
Europe
Facebook
Fashion
Fiji
Finance
Finland
Fitness
Food
France
Gabon
Gambia
Games
Gardening
Georgia
Germany
Ghana
Gibraltar
Google
Greece
Greenland
Guam
Guatemala
Guernsey
Guinea
Guyana
Haiti
Happiness
Health
Hiking
History
Home
Honduras
Hong Kong
Hungary
Iceland
India
Indonesia
Instagram
Iran
Iraq
Ireland
Isle of Man
Israel
Italy
Jamaica
Japan
Jersey
Jobs
Jordan
Kazakhstan
Kenya
Korea
Kuwait
Kyrgyzstan
Latvia
Lebanon
Liberia
Libya
Liechtenstein
Lithuania
Love
Luxembourg
Macao
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Martinique
Mauritania
Mauritius
Meditation
Mexico
Mindfulness
Minimalism
Monaco
Mongolia
Montenegro
Montserrat
Morocco
Motivation
Movies
Mozambique
Music
Myanmar
Namibia
Nepal
Netherlands
New Zealand
News
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Nutrition
Oman
Pakistan
Palau
Palestine, State of
Panama
Papua New Guinea
Paraguay
Parenting
Peru
Pets
Philippines
Philosophy
Photography
Podcasts
Poetry
Poland
Politics
Portugal
Productivity
Psychology
Puerto Rico
Qatar
Real estate
Recipes
Relationships
Romania
Russian Federation
Rwanda
Réunion
Samoa
San Marino
Saudi Arabia
Science
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Somalia
South Africa
South Sudan
Space
Spain
Sports
Sri Lanka
Startups
Stock
Sudan
Suriname
Sustainability
Sweden
Switzerland
Taiwan
Tajikistan
Technology
Thailand
TikTok
Tonga
Travel
Tunisia
Turkey
Turkmenistan
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Vegan
Viet Nam
Virgin Islands, U.S.
Virtual Reality
Weather
World
Yemen
Yoga
YouTube
Zambia
Zimbabwe

There are no more issues here either.

#### Attribute `published_at`

Format the published_at field as RFC 3339 (ISO 8601 string):

In [29]:
import pandas as pd

dataset['published_at'] = pd.to_datetime(dataset['published_at'], format='mixed')
dataset['published_at'] = dataset['published_at'].dt.strftime('%Y-%m-%dT%H:%M:%SZ')

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,Nepal,UN Secretary-General Antonio Guterres urged th...
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06T01:20:24Z,Nepal,At least 14 persons lost their lives and more ...
6,Al Jazeera English,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25T09:58:17Z,Nepal,"India, the first non-Arab country to recognise..."
7,The Indian Express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02T05:48:58Z,Nepal,Written by Alex Travelli and Hari Kumar No nat...
12,The Times of India,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02T01:12:47Z,Nepal,NEW DELHI: India preferred Bangladesh over Nep...
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29T10:57:22Z,Home,Karnataka Deputy Chief Minister D K Shivakumar...
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29T08:41:18Z,Home,FC Barcelona have guaranteed at least $767.6 m...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29T10:01:12Z,Home,The photo from David and Sarah Lubarsky's wedd...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29T13:44:33Z,Home,Kerber’s Farm: Bringing Farm To Table To Manha...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,Home,Cofounder at UpperKey. Passionate about proper...

#### Attribute `title`

We will remove all rows where the `title` length exceeds the length of the `full_content` text:

In [30]:
dataset = dataset[dataset['title'].str.len() < dataset['full_content'].str.len()]

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,Nepal,UN Secretary-General Antonio Guterres urged th...
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06T01:20:24Z,Nepal,At least 14 persons lost their lives and more ...
6,Al Jazeera English,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25T09:58:17Z,Nepal,"India, the first non-Arab country to recognise..."
7,The Indian Express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02T05:48:58Z,Nepal,Written by Alex Travelli and Hari Kumar No nat...
12,The Times of India,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02T01:12:47Z,Nepal,NEW DELHI: India preferred Bangladesh over Nep...
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29T10:57:22Z,Home,Karnataka Deputy Chief Minister D K Shivakumar...
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29T08:41:18Z,Home,FC Barcelona have guaranteed at least $767.6 m...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29T10:01:12Z,Home,The photo from David and Sarah Lubarsky's wedd...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29T13:44:33Z,Home,Kerber’s Farm: Bringing Farm To Table To Manha...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,Home,Cofounder at UpperKey. Passionate about proper...

The `title` usually captures the essence of the article, and its presence within the text can enhance semantic search in certain cases. We will merge the `title` with the main body using a structural highlighting method.

In [31]:
dataset['full_content'] = (
    "Title: " + dataset['title'] + 
    ". Content: " + dataset['full_content']
)

dataset

,source_name,title,url,published_at,category,full_content
0,International Business Times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,Nepal,Title: UN Chief Urges World To 'Stop The Madne...
3,The Indian Express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06T01:20:24Z,Nepal,Title: Sikkim warning: Hydroelectricity push m...
6,Al Jazeera English,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25T09:58:17Z,Nepal,Title: Pro-Israel rallies allowed in India but...
7,The Indian Express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02T05:48:58Z,Nepal,Title: No nation in the world is buying more p...
12,The Times of India,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02T01:12:47Z,Nepal,Title: PM Hasina’s war on terror gets daughter...
...,...,...,...,...,...,...
105370,The Indian Express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29T10:57:22Z,Home,"Title: Have done no wrong, only did party work..."
105371,Forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29T08:41:18Z,Home,Title: FC Barcelona Guarantees $77.6 Million C...
105372,NPR,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29T10:01:12Z,Home,Title: Three hospitals ignored her gravely ill...
105373,Forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29T13:44:33Z,Home,Title: Kerber’s Farm: Bringing Farm To Table T...
105374,Forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,Home,Title: Tips For Investing In Short-Term Rental...

The search will return a URL to the article. We will remove the `title` field, as it is no longer needed.

In [ ]:
# dataset = dataset.drop('title', axis=1)

# dataset

,source_name,url,published_at,category,full_content
0,International Business Times,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,Nepal,Title: UN Chief Urges World To 'Stop The Madne...
3,The Indian Express,https://indianexpress.com/article/opinion/edit...,2023-10-06T01:20:24Z,Nepal,Title: Sikkim warning: Hydroelectricity push m...
6,Al Jazeera English,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25T09:58:17Z,Nepal,Title: Pro-Israel rallies allowed in India but...
7,The Indian Express,https://indianexpress.com/article/business/avi...,2023-11-02T05:48:58Z,Nepal,Title: No nation in the world is buying more p...
12,The Times of India,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02T01:12:47Z,Nepal,Title: PM Hasina’s war on terror gets daughter...
...,...,...,...,...,...
105370,The Indian Express,https://indianexpress.com/article/cities/banga...,2023-11-29T10:57:22Z,Home,"Title: Have done no wrong, only did party work..."
105371,Forbes,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29T08:41:18Z,Home,Title: FC Barcelona Guarantees $77.6 Million C...
105372,NPR,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29T10:01:12Z,Home,Title: Three hospitals ignored her gravely ill...
105373,Forbes,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29T13:44:33Z,Home,Title: Kerber’s Farm: Bringing Farm To Table T...
105374,Forbes,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,Home,Title: Tips For Investing In Short-Term Rental...

#### Normalization metadata fileds

To prevent case mismatches during metadata filtering, all fields will be lowercased. Similarly, we'll apply this in Qdrant for all string-based metadata to maintain consistency.

In [32]:
for col in ['source_name', 'category']:
    dataset[col] = dataset[col].str.lower()

dataset

,source_name,title,url,published_at,category,full_content
0,international business times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,nepal,Title: UN Chief Urges World To 'Stop The Madne...
3,the indian express,Sikkim warning: Hydroelectricity push must be ...,https://indianexpress.com/article/opinion/edit...,2023-10-06T01:20:24Z,nepal,Title: Sikkim warning: Hydroelectricity push m...
6,al jazeera english,Pro-Israel rallies allowed in India but Palest...,https://www.aljazeera.com/news/2023/10/25/pro-...,2023-10-25T09:58:17Z,nepal,Title: Pro-Israel rallies allowed in India but...
7,the indian express,No nation in the world is buying more planes t...,https://indianexpress.com/article/business/avi...,2023-11-02T05:48:58Z,nepal,Title: No nation in the world is buying more p...
12,the times of india,PM Hasina’s war on terror gets daughter India’...,https://timesofindia.indiatimes.com/india/pm-h...,2023-11-02T01:12:47Z,nepal,Title: PM Hasina’s war on terror gets daughter...
...,...,...,...,...,...,...
105370,the indian express,"Have done no wrong, only did party work, says ...",https://indianexpress.com/article/cities/banga...,2023-11-29T10:57:22Z,home,"Title: Have done no wrong, only did party work..."
105371,forbes,FC Barcelona Guarantees $77.6 Million Champion...,https://www.forbes.com/sites/tomsanderson/2023...,2023-11-29T08:41:18Z,home,Title: FC Barcelona Guarantees $77.6 Million C...
105372,npr,Three hospitals ignored her gravely ill fiancé...,https://www.npr.org/2023/11/29/1215016001/heal...,2023-11-29T10:01:12Z,home,Title: Three hospitals ignored her gravely ill...
105373,forbes,Kerber’s Farm: Bringing Farm To Table To Manha...,https://www.forbes.com/sites/garystern/2023/11...,2023-11-29T13:44:33Z,home,Title: Kerber’s Farm: Bringing Farm To Table T...
105374,forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,home,Title: Tips For Investing In Short-Term Rental...

Save the cleaned dataset:

In [33]:
dataset.to_parquet("dataset.parquet.gzip", compression="gzip")

## Additional functions

Function for measuring search delays:

In [66]:
import time
import requests
import pandas as pd
from typing import Callable

BENCHMARK_COLS = [
    "latency_mean_ms",
    "latency_p50_ms",
    "latency_p90_ms",
    "latency_p95_ms",
    "latency_p99_ms",
]

latency_results = pd.DataFrame(columns=BENCHMARK_COLS)


def benchmark_search(fn: Callable, result_df: pd.DataFrame, test_name: str, warmup_runs: int = 3, n_runs: int = 20) -> pd.DataFrame:
    
    rows = []

    # Warmup search
    for _ in range(warmup_runs):
        fn()

    # Measurements
    for _ in range(n_runs):
        t0 = time.perf_counter()
        fn()
        latency_ms = (time.perf_counter() - t0) * 1000
        rows.append(latency_ms)

    # Calculate latency metrics
    stats = pd.Series(rows)
    metrics = stats.describe(percentiles=[0.5, 0.9, 0.95, 0.99]) #.round(2)
    
    # Update results
    result_df.loc[test_name] = [
        metrics["mean"],     # latency_mean_ms
        metrics["50%"],      # latency_p50_ms
        metrics["90%"],      # latency_p90_ms
        metrics["95%"],      # latency_p95_ms
        metrics["99%"]       # latency_p99_ms
    ]

    return result_df


def google_search(query: str) -> str:
    return requests.get("https://www.google.com/search", params={"q": query}, timeout=10).text

def duckduckgo_search(query: str) -> str:
    return requests.get("https://html.duckduckgo.com/html/", params={"q": query}, timeout=10).text


benchmark_search(lambda: google_search("python pandas"), latency_results, "Google search")
benchmark_search(lambda: duckduckgo_search("python pandas"), latency_results, "DuckDuckGo search")

latency_results

,latency_mean_ms,latency_p50_ms,latency_p90_ms,latency_p95_ms,latency_p99_ms
Google search,578.534937,549.386218,623.097373,699.069694,1072.207576
DuckDuckGo search,395.736543,398.374213,413.218756,418.955833,420.266133

A function for measuring ranking and search metrics:

In [67]:
import pandas as pd
from ranx import Qrels, Run, evaluate

# Ваши столбцы
metrics = ["mrr", "recall@10", "ndcg@10"]
metrics_results = pd.DataFrame(columns=metrics)

def calculate_search_metrics(predicted, ground_truth, metrics, test_name, results_df):
    query_id = "test_query"
    
    # Ground Truth with weghts
    gt_data = Qrels({
        query_id: {
            doc_id: len(ground_truth) - i 
            for i, doc_id in enumerate(ground_truth)
        }
    })
    
    # Search results with weights
    pd_data = Run({
        query_id: {
            doc_id: len(predicted) - i 
            for i, doc_id in enumerate(predicted)
        }
    })
    
    # Calculating metrics
    scores = evaluate(gt_data, pd_data, metrics)
    
    # Updating DataFrame with results
    results_df.loc[test_name] = [scores.get(col, 0.0) for col in metrics]


truth = ["doc_A", "doc_B", "doc_C"]

# Test 1: Perfect order (the same as in truth)
calculate_search_metrics(["doc_A", "doc_B", "doc_C"], truth, metrics, "perfect_order", metrics_results)

# Test 2: The same documents, but in reverse order
calculate_search_metrics(["doc_C", "doc_B", "doc_A"], truth, metrics, "reversed_order", metrics_results)

# Test 3: The same documents, but the first one (most important) is missing
calculate_search_metrics(["doc_B", "doc_C"], truth, metrics, "missing_top_1", metrics_results)

print(metrics_results)

                mrr  recall@10   ndcg@10
perfect_order   1.0   1.000000  1.000000
reversed_order  1.0   1.000000  0.789998
missing_top_1   1.0   0.666667  0.552500

Функция для подготовки данных перед загрузкой с учётом определенного сплиттера:

In [ ]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
import pandas as pd

encoder = SentenceTransformer("intfloat/multilingual-e5-base", device="cuda")

text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=300,
        chunk_overlap=30,
    )

def dataset_stream(df, splitter, gpu_batch_size=64):
    meta_cols = ["source_name", "title", "url", "published_at", "category"]
    
    batch_texts = []
    batch_payloads = []
    
    for row in df.itertuples(index=False):
        # Базовые метаданные текущей строки
        payload_base = {col: getattr(row, col) for col in meta_cols}
        
        # Режем текст переданным сплиттером
        chunks = splitter.split_text(str(row.full_content))
        
        for chunk in chunks:
            batch_texts.append(f"passage: {chunk}")
            # Добавляем сам чанк в метаданные, чтобы видеть его при поиске
            current_payload = payload_base.copy()
            current_payload["text"] = chunk
            batch_payloads.append(current_payload)
            
            # Если набрали батч для GPU — кодируем и отдаем
            if len(batch_texts) == gpu_batch_size:
                vectors = encoder.encode(batch_texts, convert_to_numpy=True)
                for v, p in zip(vectors, batch_payloads):
                    yield v, p
                batch_texts, batch_payloads = [], []
                
    # Sending the remaining items
    if batch_texts:
        vectors = encoder.encode(batch_texts, convert_to_numpy=True)
        for v, p in zip(vectors, batch_payloads):
            yield v, p

test_df = pd.read_parquet("dataset.parquet.gzip")[:128]

dataset_streamer = dataset_stream(test_df, text_splitter)

embeddings, payloads = next(dataset_streamer)

print(embeddings.shape, payloads)

del encoder, text_splitter, dataset_streamer, test_df

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

(768,) {'source_name': 'international business times', 'title': "UN Chief Urges World To 'Stop The Madness' Of Climate Change", 'url': 'https://www.ibtimes.com/un-chief-urges-world-stop-madness-climate-change-3716939', 'published_at': '2023-10-30T10:12:35Z', 'category': 'nepal', 'text': 'Title: UN Chief Urges World To \'Stop The Madness\' Of Climate Change. Content: UN Secretary-General Antonio Guterres urged the world Monday to "stop the madness" of climate change as he visited Himalayan regions struggling from rapidly melting glaciers to witness the devastating impact of the'}

В некоторых случаях можно сразу подготовить все данные и просто загружать их методом `client.upload_collection()`.

## Setting Up the Development Environment

### Подключение к хранилищу

Connect to the local Qdrant storage:

> [Access to the Qdrant dashboard from Docker host](http://localhost:6333/dashboard)

In [5]:
from qdrant_client import QdrantClient, models
import os

client = QdrantClient(url=os.getenv("QDRANT_URL"), api_key=os.getenv("QDRANT_API_KEY"))

collections = client.get_collections()
print(f"Connected to Qdrant Cloud: {len(collections.collections)} collections")

Connected to Qdrant Cloud: 1 collections

/tmp/ipykernel_685/396165620.py:4: UserWarning: Api key is used with an insecure connection.
  client = QdrantClient(url=os.getenv("QDRANT_URL"), api_key=os.getenv("QDRANT_API_KEY"))

### Выбор модели для плотных векторов

В качестве модели для создания Dense Vectors эмбеддингов выберем `multilingual-e5-base`

In [3]:
from langchain_huggingface import HuggingFaceEmbeddings

encoder = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-base", model_kwargs={"device": "cuda"})

text = "Привет, мир!"
vector = encoder.embed_query(text)

print(f"Vector length: {len(vector)}, \n {vector}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Vector length: 768,
 [0.02919846773147583, 0.04641994461417198, -0.015342864207923412, 0.04352734982967377, 0.005529590882360935, -0.041299235075712204, -0.018318360671401024, -0.008249619975686073, 0.019141297787427902, 0.036783359944820404, -0.02454104833304882, -0.004741741809993982, 0.19188784062862396, 0.04812153801321983, -0.03860395774245262, -0.06411952525377274, -0.0035166272427886724, -0.030167503282427788, 0.004394894931465387, 0.0036365268751978874, 0.05462142825126648, -0.02209370583295822, 0.04198655113577843, -0.0461546927690506, 0.04129008203744888, -0.01138180959969759, 0.021426254883408546, 0.006927143782377243, -0.018990570679306984, 0.012140760198235512, 0.02302173711359501, -0.05457295849919319, 0.027344875037670135, 0.007848447188735008, 0.005846124142408371, 0.044427674263715744, -0.008338356390595436, -0.02434696815907955, 0.04735226929187775, 0.004183465614914894, 0.028512168675661087, 0.031187385320663452, -0.011971750296652317, -0.008447249419987202, 0.036498744040727615, 0.014495289884507656, 0.02854660525918007, 0.01116136834025383, -0.031685858964920044, -0.0511636883020401, 0.025273077189922333, 0.02566458471119404, 0.03193308785557747, 0.012465323321521282, -0.07679077982902527, -0.03502047061920166, 0.05034615471959114, 0.03859001770615578, -0.07133247703313828, 0.04493261128664017, -0.0031943509820848703, -0.01731007732450962, 0.011768314056098461, -0.010773811489343643, 0.04128137230873108, -0.030671488493680954, -0.029310453683137894, -0.018369533121585846, -0.030275605618953705, -0.008421512320637703, -0.0004149206797592342, 0.0009903268655762076, 0.03782916069030762, -0.011429550126194954, -0.03276354819536209, -0.02505902387201786, -0.030890876427292824, 0.01941756159067154, -0.029292520135641098, -0.028187895193696022, 0.02657344751060009, -0.011172774247825146, 0.05068116635084152, 0.011577106080949306, 0.0021377946250140667, -0.06466314196586609, -0.04230448976159096, 0.026065940037369728, 0.023922165855765343, 0.042376771569252014, 0.003203578758984804, -0.018576787784695625, -0.037798017263412476, 0.01070238184183836, 0.008491112850606441, -0.012632058002054691, -0.006289660464972258, 0.03282458707690239, 0.024656055495142937, -0.04558471962809563, -0.0028442898765206337, -0.05834909901022911, -0.023936765268445015, -0.024364760145545006, -0.04847745969891548, -0.013053539209067822, 0.016856223344802856, -0.017519861459732056, 0.036069002002477646, -0.00887343194335699, -0.050342857837677, 0.027199137955904007, 0.03716334328055382, -0.06713592261075974, 0.0037270260509103537, -0.02267126366496086, 0.034664902836084366, -0.03366733714938164, -0.00390980439260602, -0.045171745121479034, 0.0006617024191655219, 0.01424438040703535, -0.028827546164393425, -0.022657187655568123, 0.022773003205657005, -0.022103898227214813, -0.0018731130985543132, -0.012029353529214859, 0.04854822903871536, 0.005915109999477863, 0.014667206443846226, -0.04009571671485901, -0.0025680537801235914, 0.016292329877614975, -0.0449957400560379, 0.0672614797949791, 0.007536525838077068, 0.025899678468704224, 0.02334228716790676, 0.002846179064363241, 0.022378508001565933, -0.04006095603108406, 0.03128581494092941, 0.006604294758290052, 0.03185245394706726, -0.0784987136721611, 0.007829523645341396, 0.00022630579769611359, -0.04294649511575699, 0.06515923142433167, 0.03686480224132538, 0.005482812877744436, -0.05435309186577797, -0.039369963109493256, 0.04758583754301071, -0.015122273936867714, -0.07241114974021912, -0.027789533138275146, -0.017157774418592453, 0.04154569283127785, 0.0339629091322422, 0.02278997376561165, 0.03204851970076561, 0.001953302649781108, 0.030985506251454353, 0.0026950135361403227, -0.014784194529056549, 0.01628604717552662, -0.018130440264940262, -0.05940468981862068, -0.031324032694101334, 0.005007073283195496, -0.0552409328520298, 0.028821468353271484, 0.010993914678692818, -0.029546713456511497, -0.0087928157299757, -0.03896162658929825, -0.01813642680644989, -0.05975183844566345, -0.03503567725419998, -0.041837625205516815, 0.00023422054073307663, 0.04028269648551941, -0.014302504248917103, -0.01228068582713604, -0.002316301455721259, -0.01757834292948246, -0.012903442606329918, 0.005941626615822315, 0.010362117551267147, 0.05560746416449547, 0.0347055085003376, 0.04637514054775238, 0.014824091456830502, -0.006075466517359018, 0.026283081620931625, 0.029664436355233192, -0.019734160974621773, -0.028309699147939682, 0.03809606283903122, -0.010872147977352142, 0.026680488139390945, 0.04368046298623085, -0.019363023340702057, -0.08315571397542953, 0.04699958488345146, 0.0361761748790741, 0.020357424393296242, 0.028319666162133217, -0.015122368931770325, 0.06009663641452789, -0.02185317501425743, 0.021554674953222275, -0.013238819316029549, -0.05260783061385155, 0.024004030972719193, 0.01076042652130127, 0.0005337275215424597, 0.021095944568514824, 0.055101178586483, -0.03668088838458061, 0.039391834288835526, -0.0012478844728320837, -0.02142285369336605, 0.04317295923829079, 0.04343823716044426, -0.005291401408612728, 0.020601503551006317, 0.009544627740979195, 0.06829530000686646, 0.008979425765573978, -0.050756197422742844, 0.03050970658659935, -0.032784558832645416, -0.019487574696540833, 0.06151096522808075, 0.001315684407018125, -0.040815189480781555, -0.1272372454404831, -0.04180978238582611, 0.0064158025197684765, 0.028559379279613495, -0.0066576008684933186, 0.02422056719660759, -0.04679269716143608, -0.006155712064355612, 0.02955862320959568, -0.04551639407873154, -0.011443663388490677, 0.027414023876190186, -0.036630261689424515, 0.002325418870896101, -0.008665302768349648, 0.01885753683745861, 5.7600300351623446e-05, -0.03708023577928543, 0.006206164136528969, -0.03140190243721008, 0.008099154569208622, -0.014620939269661903, -0.04741150513291359, -0.02965192310512066, -0.021761370822787285, 0.004856828134506941, 0.015557661652565002, 0.058934181928634644, -0.026933766901493073, 0.003648114623501897, -0.008671321906149387, -0.053416658192873, -0.017403917387127876, -0.05862098187208176, 0.086607925593853, 0.005912510212510824, -0.032000862061977386, -0.0811256393790245, 0.04098864272236824, -0.02702917717397213, -0.007672344800084829, -0.04417536407709122, 0.07480476051568985, -0.02677352912724018, -0.03855307772755623, -0.03843453899025917, 0.007371833082288504, -0.06934797763824463, 0.019567415118217468, -0.04960023984313011, 0.01144980639219284, 0.04048730432987213, 0.06629988551139832, -0.016750775277614594, -0.006153540685772896, 0.04549865052103996, 0.03593884035944939, 0.06192967668175697, -0.023420093581080437, 0.037614043802022934, 0.019591661170125008, -0.01895030215382576, -0.035304803401231766, 0.0736512839794159, -0.0412890762090683, -0.04106004163622856, -0.004048531409353018, 0.09137619286775589, 0.01958266645669937, -0.05418061465024948, 0.029363352805376053, -0.035256631672382355, -0.03895631432533264, -0.06391657143831253, 0.031704701483249664, 0.04180352762341499, -0.04025334492325783, 0.004623030312359333, 0.08524110168218613, 0.008186005055904388, 0.06433339416980743, -0.02709035575389862, 0.030221495777368546, -0.025104515254497528, -0.055204279720783234, 0.03194744139909744, 0.020188022404909134, 0.011481271125376225, 0.007701297756284475, 0.08771345764398575, 0.009612246416509151, -0.028066709637641907, 0.024068748578429222, 0.005063581746071577, 0.05002259835600853, -0.057357560843229294, -0.009505104273557663, -0.02425478771328926, -0.05265592783689499, 0.022998010739684105, 0.04374941065907478, -0.039241209626197815, 0.028140874579548836, -0.014968659728765488, -0.007813100703060627, 0.03234673663973808, -0.04477725923061371, -0.025413228198885918, -0.005108980927616358, -0.011700516566634178, 0.03779131919145584, 0.028909873217344284, -0.0047656153328716755, 0.016744917258620262, 0.008482979610562325, -0.008514473214745522, -0.010340646840631962, 0.055120669305324554, -0.00994759239256382, -0.019531022757291794, -0.018337761983275414, -0.022557884454727173, 0.03660024702548981, 0.0010702010476961732, -0.008425119332969189, 0.022620107978582382, 0.030315537005662918, -0.010219861753284931, -0.003143925219774246, 0.03095749393105507, -0.02731472998857498, 0.09801314026117325, 0.040072280913591385, -0.021131325513124466, -0.03552170842885971, 0.026655100286006927, -0.012773988768458366, 0.061796776950359344, -0.03558671474456787, -0.016484634950757027, 0.049366213381290436, 0.0717288926243782, 0.02152479998767376, 0.023321541026234627, 0.01688135229051113, -0.03390824794769287, 0.04132403805851936, 0.03167792409658432, -0.06741505116224289, 0.05872993916273117, -0.022460374981164932, -0.020537596195936203, -0.05561501160264015, -0.030841967090964317, 0.009960564784705639, 0.021721575409173965, -0.00048210867680609226, 0.04862245172262192, -0.018404318019747734, -0.014394872821867466, -0.03233680874109268, 0.027766700834035873, 0.0016187018482014537, -0.010554364882409573, 0.01576673425734043, 0.024823572486639023, 0.008554351516067982, -0.010293139144778252, 0.047461073845624924, 0.0033400102984160185, -0.005307219922542572, 0.03412846475839615, -0.03334908187389374, 0.045025646686553955, 0.022305164486169815, -0.017679693177342415, -0.0013013220159336925, -0.015343639068305492, 0.05206776037812233, 0.06642080098390579, 0.0016850186511874199, -0.06392964720726013, 0.00975827220827341, 0.023014429956674576, -0.0028994090389460325, 0.03448224812746048, -0.08468083292245865, -0.047853022813797, -0.038234543055295944, 0.02065822295844555, -0.05788765475153923, -0.020238669589161873, 0.01826990768313408, 0.013598037883639336, 0.007801563944667578, 0.03359154611825943, -0.03167916089296341, 0.04488539323210716, -0.00316335610114038, -0.015490954741835594, 0.04168199375271797, 0.009615241549909115, 0.009768279269337654, -0.0009318668744526803, -0.01167029794305563, -0.050923146307468414, 0.003502899780869484, -0.023105360567569733, 0.012082663364708424, -0.011792433448135853, -0.01911296509206295, 0.013959594070911407, 0.02249496802687645, 0.016586538404226303, -0.018699008971452713, 0.053551558405160904, -0.04744932800531387, 0.020386889576911926, -0.03497157245874405, 0.014695795252919197, -0.09123020619153976, 0.039883531630039215, 0.05706897750496864, -0.00455901026725769, -0.04463045299053192, -0.021880095824599266, -0.06499487906694412, 0.027653954923152924, -0.04598761722445488, -0.029020950198173523, -0.007952467538416386, -0.021596865728497505, -0.012700160965323448, 0.03129081055521965, -0.011723501607775688, 0.03253176063299179, 0.037298887968063354, -0.010920903645455837, 0.07862541824579239, 0.03707485646009445, -0.030814681202173233, -0.00912800244987011, -0.004016447346657515, -0.039218924939632416, 0.013895013369619846, 0.023999616503715515, 0.043387364596128464, -0.08673018217086792, 0.06569365411996841, 0.05685679242014885, -0.042037978768348694, 0.004085375927388668, 0.02599545381963253, 0.04213542491197586, 0.0033962817396968603, -0.010994833894073963, 0.04403271898627281, -0.04912062734365463, -0.0852348804473877, 0.03165842592716217, 0.015804121270775795, -0.030205877497792244, -0.025688737630844116, -0.05070813000202179, 0.00957981962710619, -0.05702544376254082, 0.031535565853118896, -0.06479746103286743, -0.05597307160496712, 0.03199532628059387, -0.035887327045202255, 0.1439499408006668, -0.07195580750703812, -0.028409477323293686, -0.031511858105659485, 0.04023703932762146, -0.007228350732475519, -0.011981089599430561, 0.02462487667798996, 0.010757640935480595, -0.0050452696159482, 0.02297445572912693, 0.007694986183196306, -0.042571358382701874, -0.01488521322607994, 0.03607065603137016, -0.04477742686867714, 0.020793281495571136, -0.05990740284323692, 0.031569235026836395, -0.04096848890185356, 0.04034321755170822, -0.034323401749134064, 0.020660752430558205, -0.06215825304389, -0.07955758273601532, 0.001380514120683074, -0.006177408155053854, -0.019872073084115982, 0.021847518160939217, -0.02619604393839836, 0.014017234556376934, -0.04166271910071373, 0.03284741938114166, -0.03299465775489807, 0.03718999773263931, -0.054450854659080505, 0.004040243104100227, 0.0006845351890660822, 0.011959516443312168, -0.01408160850405693, 0.019376739859580994, 0.005443130619823933, 0.013501915149390697, 0.04963383823633194, -0.0502389594912529, 0.007369419559836388, -0.01216506864875555, 0.04549098014831543, -0.013062273152172565, -0.031246541067957878, -0.00586974760517478, -0.01061159186065197, -0.003811750328168273, 0.04377992823719978, -0.01149666402488947, 0.036453235894441605, 0.02359006181359291, -0.015793096274137497, -0.050159405916929245, 0.04427587613463402, -0.08944258838891983, 0.004065241664648056, 0.044152501970529556, -0.020702501758933067, 0.06042225658893585, 0.029723772779107094, -0.03410264849662781, -0.03558730706572533, 0.033320944756269455, -0.03508137911558151, -0.026538772508502007, -0.011791607365012169, -0.03921262174844742, 0.0306510329246521, -0.018659064546227455, 0.024696623906493187, 0.03567277267575264, -0.01597682572901249, -0.18700723350048065, 0.03687962517142296, -0.014410912059247494, -0.04658541828393936, 0.0313882939517498, 0.012614638544619083, 0.02692563831806183, -0.011968876235187054, 0.009356547147035599, 0.0032209595665335655, 0.030909184366464615, -0.043319109827280045, 0.052870046347379684, -0.012390733696520329, -0.035652436316013336, 0.013468793593347073, -0.03829938545823097, -0.06706921011209488, 0.02624541148543358, 0.03623230755329132, 0.02698812261223793, 0.07180063426494598, -0.008088022470474243, 0.009412509389221668, -0.03550206497311592, -0.03908671438694, -0.0326208733022213, 0.03605865314602852, 0.03995031490921974, 0.02639838494360447, -0.008582797832787037, 0.025160200893878937, 0.03930835425853729, 0.02694597654044628, -0.009544581174850464, -0.0024334825575351715, -0.02560761384665966, 0.02083631046116352, -0.0317186638712883, 0.04539129137992859, 0.01144548412412405, -0.06633827090263367, -0.012682812288403511, 0.014208242297172546, -0.02210187166929245, 0.05021267384290695, 0.03153865411877632, 0.02491690218448639, -0.06241132691502571, -0.017903784289956093, 0.06954009085893631, 0.007522630970925093, -0.07970336824655533, -0.014356025494635105, -0.002825092989951372, 0.04343774914741516, 0.015479039400815964, 0.03191426768898964, 0.018460309132933617, -0.019611932337284088, 0.0069756763987243176, 0.05884816497564316, -0.006293962709605694, 0.028521262109279633, -0.028040166944265366, 0.007770332973450422, 0.00978792179375887, -0.051526617258787155, -0.024609524756669998, 0.014258277602493763, 0.025851313024759293, -0.03284288942813873, -0.024697251617908478, 0.037990059703588486, 0.011045455001294613, -0.003249814035370946, 0.024505268782377243, -0.030123118311166763, -0.06289629638195038, 0.00030547170899808407, -0.00865925569087267, -0.03426608070731163, 0.007306480314582586, 0.023459499701857567, -0.03112815134227276, -0.014568119309842587, 0.010768335312604904, 0.014426687732338905, 0.02124374732375145, 0.0220491960644722, -0.014068307355046272, -0.011014387011528015, 0.03150402382016182, 0.016352657228708267, 0.027806589379906654, -0.02588854730129242, -0.021250227466225624, 0.03785985708236694, -0.014422867447137833, -0.019948579370975494, -0.006598041858524084, -0.03870854899287224, 0.0007902105571702123, 0.028758812695741653, 0.04756801202893257, -0.03156869113445282, -0.08216160535812378, 0.049449458718299866, 0.004001905210316181, -0.014948497526347637, 0.01917104795575142, 0.026458194479346275, 0.034287650138139725, -0.01937895454466343, 0.0021876979153603315, -0.008130262605845928, 0.02665361575782299, -0.04875066503882408, -0.027958374470472336, -0.029596909880638123, -0.01595967449247837, -0.034233469516038895, 0.03125294670462608, 0.005466204136610031, 0.060450229793787, 0.008907729759812355, -0.006178054492920637, 0.020860936492681503, 0.039581313729286194, 0.04859379678964615, -0.029441768303513527, -0.067444808781147, 0.004971241112798452, -0.03900231793522835, -0.0265815332531929, 0.02437025122344494, 0.03346853330731392, -0.012652197852730751, 0.03849519044160843, 0.05576622113585472, 0.04681120440363884, -0.0409829281270504, -0.009865914471447468, -0.02738293632864952, -0.037186089903116226, 0.02126423642039299, 0.03841295838356018, -0.0366545170545578, 0.016581280156970024, -0.005224417429417372, -0.029215140268206596, -0.07598632574081421, -0.002296107355505228, -0.015654345974326134, -0.024247612804174423, -0.000480042421258986, 0.008606243878602982, -0.002031471813097596, -0.027737034484744072, -0.00011080606054747477, -0.03469814732670784, -0.04729015380144119, 0.042851123958826065, 0.03191974014043808, 0.031082456931471825, 0.005123976618051529, -0.004106893204152584, 0.006586886942386627, 0.005140718072652817, 0.04202674701809883, -0.01398961991071701, 0.019961711019277573, 0.02492917887866497, 0.009449504315853119, 0.03229576721787453, -0.014476820826530457, 0.013597751967608929, -0.04536212235689163, -0.01808924414217472, 0.009224147535860538]

## Плотные вектора - стратегия фрагментации текста

### Выбор метрики для плотных векторов

В качестве метрики выбрано косинусное сходство (Cosine Similarity), так как модели из семейства E5 обучались с использованием функции потерь, которая оптимизирует именно косинусное расстояние. Это значит, что семантическая близость текстов в векторном пространстве модели напрямую соответствует углу между векторами.

Кроме того, косинусное сходство учитывает только направление векторов, игнорируя их длину (норму). Если один и тот же смысл выражен кратко или чуть более развернуто, косинусное сходство сочтет их близкими.

### Выбор оптимальной страгении фрагментации текста

Выбор стратегии чанкинга (разбиения текста) — это 50% успеха в RAG. В 2026 году, когда модели вроде multilingual-e5-base стали стандартом, подход к подготовке данных сильно сместился в сторону сохранения семантической целостности.

Кратко вспомним какие стратегии чанкинга существуют и оценим насколько они эффективны:
- Fixed-Size Chunking - это самый примитивный метод. Он часто разрывает предложения на полуслове, из-за чего теряется смысл. Нет смысла рассматривать.
- Sentence-Based Chunking - одиночное предложение часто не содержит достаточно контекста для полноценного ответа. Вектор одного предложения в E5 может быть слишком специфичным и не поймать общую тему документа. Не рассматриваем.
- Sliding Window Chunking - Чанки фиксированного размера, но с перекрытием (overlap), например, 512 токенов с нахлестом в 50-100 токенов. Перекрытие гарантирует, что контекст, который мог быть разорван на границе чанков, сохранится хотя бы в одном из них. Для RAG это критически важно для связности ответов. Но в 2026 году нет смысла использовать Sliding Window, если рассматривается Recursive Character Text Splitting.
- Recursive Character Text Splitting - пытается разбить текст по абзацам, если абзац слишком велик — по предложениям, если и они велики — по словам. Это "золотой стандарт". Он сохраняет структуру текста (сначала пытается оставить абзац целым) и гарантирует, что чанк впишется в max_seq_length (512 токенов для выбранной модели). Рассматриваем.
- Semantic-Aware Chunking - Текст разбивается там, где резко меняется смысл (анализируется расстояние между эмбеддингами соседних предложений). Это позволяет создавать «умные» границы, где каждый фрагмент — это законченная мысль. Для моделей семейства E5 это лучший компаньон, так как модель будет работать с идеально чистыми по смыслу кусками. Рассматриваем.

#### Получение тестовой выборки

Проверять каждую стратегию чанкинга на всем датасете слишком затратно по рессурсам, возьмём фрагмент датасета размером в 1500 новостных статей методом стратифицированной выборки:

In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split

dataset = pd.read_parquet("dataset.parquet.gzip")

sample_size = 300 # 1500

samples, _ = train_test_split(
    dataset,
    train_size=(sample_size / len(dataset)),
    stratify=dataset['category'],  # Ключевой параметр для баланса категорий
    random_state=42           # Фиксируем результат для воспроизводимости
)

samples

,source_name,title,url,published_at,category,full_content
60932,etf daily news,New York State Common Retirement Fund Trims St...,https://www.etfdailynews.com/2023/11/05/new-yo...,2023-11-05T12:39:26Z,stock,Title: New York State Common Retirement Fund T...
104902,globalsecurity.org,Head of Tibet's government-in-exile meets with...,https://www.globalsecurity.org/military/librar...,2023-11-29T07:27:22Z,canada,Title: Head of Tibet's government-in-exile mee...
25159,wired,Graphcore Was the UK's AI Champion—Now It’s Sc...,https://www.wired.com/story/graphcore-uk-ai-ch...,2023-10-06T11:59:00Z,technology,Title: Graphcore Was the UK's AI Champion—Now ...
46395,rt,US breaks $6 billion promise to Iran,https://www.rt.com/news/584792-us-iran-frozen-...,2023-10-13T01:55:40Z,iran,Title: US breaks $6 billion promise to Iran. C...
14951,rt,Russian Communists want gay ballet icon Nureye...,https://www.rt.com/russia/585887-russia-commun...,2023-10-26T16:21:56Z,russian federation,Title: Russian Communists want gay ballet icon...
...,...,...,...,...,...,...
64448,etf daily news,Concord Wealth Partners Raises Stock Holdings ...,https://www.etfdailynews.com/2023/11/07/concor...,2023-11-07T14:02:44Z,stock,Title: Concord Wealth Partners Raises Stock Ho...
71892,globalsecurity.org,DOD Implores Congress to Provide Ukraine Defen...,https://www.globalsecurity.org/wmd/library/new...,2023-11-10T10:05:58Z,ukraine,Title: DOD Implores Congress to Provide Ukrain...
75007,bbc news,Storm Debi yellow rain warning comes into forc...,https://www.bbc.co.uk/news/uk-scotland-north-e...,2023-11-13T10:20:42Z,weather,Title: Storm Debi yellow rain warning comes in...
81035,etf daily news,So-Young International (NASDAQ:SY) versus Mara...,https://www.etfdailynews.com/2023/11/14/so-you...,2023-11-14T15:20:45Z,finance,Title: So-Young International (NASDAQ:SY) vers...
74330,etf daily news,WidePoint (NYSEAMERICAN:WYY) Coverage Initiate...,https://www.etfdailynews.com/2023/11/11/widepo...,2023-11-11T07:32:45Z,united states,Title: WidePoint (NYSEAMERICAN:WYY) Coverage I...

Возьмём одну статью для тестирования методов чанкинга:

In [15]:
article = [dataset.loc[74616, 'full_content']]
article

['Title: Xponential Fitness (NYSE:XPOF) Price Target Lowered to $31.00 at Raymond James. Content: Xponential Fitness (NYSE:XPOF–Free Report)had its price target trimmed by Raymond James from $40.00 to $31.00 in a report issued on Wednesday,Benzingareports. The brokerage currently has a strong-buy rating on the stock. XPOF has been the topic of several other reports. Piper Sandler dropped their price objective on Xponential Fitness from $26.00 to $20.00 in a research report on Thursday, October 12th. Stifel Nicolaus initiated coverage on Xponential Fitness in a research report on Friday, October 13th. They set a hold rating and a $18.00 price objective on the stock. Citigroup dropped their price objective on Xponential Fitness from $39.00 to $30.00 in a research report on Friday, August 4th. Guggenheim dropped their price objective on Xponential Fitness from $32.00 to $30.00 and set a buy rating on the stock in a research report on Friday, September 15th. Finally, Bank of America cut Xponential Fitness from a buy rating to a neutral rating and dropped their price objective for the company from $35.00 to $16.00 in a research report on Wednesday, November 1st. Three research analysts have rated the stock with a hold rating, five have given a buy rating and one has assigned a strong buy rating to the company’s stock. According to data from MarketBeat, the company presently has an average rating of Moderate Buy and an average price target of $27.90. Get Our Latest Stock Report on XPOF Want More Great Investing Ideas?10 Stocks to Sell NOW!3 Stocks to DOUBLE This YearThe 10 Best Stocks to Own in 20237 Stocks to Buy and Hold ForeverShares ofXPOF stockopened at $13.31 on Wednesday. The stock has a market cap of $665.10 million, a price-to-earnings ratio of -5.32, a PEG ratio of 1.13 and a beta of 1.27. The business’s fifty day moving average is $15.84 and its 200 day moving average is $21.06. Xponential Fitness has a twelve month low of $11.31 and a twelve month high of $33.58. Xponential Fitness (NYSE:XPOF–Get Free Report) last released its earnings results on Tuesday, November 7th. The company reported $0.11 EPS for the quarter, missing analysts’ consensus estimates of $0.14 by ($0.03). Xponential Fitness had a negative return on equity of 17.66% and a net margin of 1.59%. The company had revenue of $80.44 million during the quarter, compared to analysts’ expectations of $74.17 million. During the same period in the prior year, the company posted $0.10 earnings per share. The company’s revenue was up 26.1% on a year-over-year basis. Equities research analysts expect that Xponential Fitness will post 0.25 earnings per share for the current fiscal year. In related news, insider Andrew Hagopian acquired 4,200 shares of the firm’s stock in a transaction dated Wednesday, August 16th. The shares were purchased at an average price of $23.15 per share, with a total value of $97,230.00. Following the completion of the purchase, the insider now directly owns 8,800 shares of the company’s stock, valued at $203,720. The purchase was disclosed in a document filed with the SEC, which can be accessed throughthe SEC website. In other Xponential Fitness news, CEOAnthony Geislerbought 21,750 shares of the business’s stock in a transaction that occurred on Tuesday, August 15th. The stock was purchased at an average price of $22.93 per share, for a total transaction of $498,727.50. Following the completion of the transaction, the chief executive officer now owns 361,565 shares of the company’s stock, valued at approximately $8,290,685.45. The transaction was disclosed in a legal filing with the Securities & Exchange Commission, which is accessible throughthe SEC website. Also, insider Andrew Hagopian bought 4,200 shares of the business’s stock in a transaction that occurred on Wednesday, August 16th. The shares were acquired at an average price of $23.15 per share, with a total value of $97,230.00. Following the transaction, the insider now directly owns 8,800 shares of the company’s stock, valued at approximately $203,720. The disclosure for this purchase can be foundhere. Insiders have purchased 27,950 shares of company stock valued at $638,508 over the last quarter. 47.86% of the stock is currently owned by company insiders. Several institutional investors have recently made changes to their positions in XPOF. Macquarie Group Ltd. grew its position in shares of Xponential Fitness by 133.2% during the second quarter. Macquarie Group Ltd. now owns 2,696 shares of the company’s stock worth $34,000 after purchasing an additional 1,540 shares in the last quarter. Point72 Hong Kong Ltd purchased a new stake in shares of Xponential Fitness during the second quarter worth about $34,000. Ameritas Investment Partners Inc. grew its position in shares of Xponential Fitness by 50.1% during the second quarter. Ameritas Investment Partners Inc. now owns 2,041 shares of the company’s stock worth $35,000 after purchasing an additional 681 shares in the last quarter. Quarry LP purchased a new position in Xponential Fitness during the 2nd quarter valued at approximately $38,000. Finally, Royal Bank of Canada grew its holdings in Xponential Fitness by 48.8% during the 2nd quarter. Royal Bank of Canada now owns 2,906 shares of the company’s stock valued at $50,000 after buying an additional 953 shares in the last quarter. Hedge funds and other institutional investors own 52.97% of the company’s stock. (Get Free Report) Xponential Fitness, Inc, through its subsidiaries, operates as a boutique fitness franchisor in North America. It offers pilates, indoor cycling, barre, stretching, rowing, dancing, boxing, running, functional training, and yoga services under the Club Pilates, Pure Barre, CycleBar, StretchLab, Row House, YogaSix, Rumble, AKT, Stride, and BFT brands.   ']

#### Recursive Character Text Splitting

In [ ]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

current_chunk_size = 500

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=current_chunk_size,
    chunk_overlap=current_chunk_size * 0.1,
)

docs = text_splitter.create_documents(article)

chunks = [doc.page_content for doc in docs]

chunks

['Title: Xponential Fitness (NYSE:XPOF) Price Target Lowered to $31.00 at Raymond James. Content: Xponential Fitness (NYSE:XPOF–Free Report)had its price target trimmed by Raymond James from $40.00 to $31.00 in a report issued on Wednesday,Benzingareports. The brokerage currently has a strong-buy rating on the stock. XPOF has been the topic of several other reports. Piper Sandler dropped their price objective on Xponential Fitness from $26.00 to $20.00 in a research report on Thursday, October',
 '$20.00 in a research report on Thursday, October 12th. Stifel Nicolaus initiated coverage on Xponential Fitness in a research report on Friday, October 13th. They set a hold rating and a $18.00 price objective on the stock. Citigroup dropped their price objective on Xponential Fitness from $39.00 to $30.00 in a research report on Friday, August 4th. Guggenheim dropped their price objective on Xponential Fitness from $32.00 to $30.00 and set a buy rating on the stock in a research report on',
 'a buy rating on the stock in a research report on Friday, September 15th. Finally, Bank of America cut Xponential Fitness from a buy rating to a neutral rating and dropped their price objective for the company from $35.00 to $16.00 in a research report on Wednesday, November 1st. Three research analysts have rated the stock with a hold rating, five have given a buy rating and one has assigned a strong buy rating to the company’s stock. According to data from MarketBeat, the company presently',
 'to data from MarketBeat, the company presently has an average rating of Moderate Buy and an average price target of $27.90. Get Our Latest Stock Report on XPOF Want More Great Investing Ideas?10 Stocks to Sell NOW!3 Stocks to DOUBLE This YearThe 10 Best Stocks to Own in 20237 Stocks to Buy and Hold ForeverShares ofXPOF stockopened at $13.31 on Wednesday. The stock has a market cap of $665.10 million, a price-to-earnings ratio of -5.32, a PEG ratio of 1.13 and a beta of 1.27. The business’s',
 'ratio of 1.13 and a beta of 1.27. The business’s fifty day moving average is $15.84 and its 200 day moving average is $21.06. Xponential Fitness has a twelve month low of $11.31 and a twelve month high of $33.58. Xponential Fitness (NYSE:XPOF–Get Free Report) last released its earnings results on Tuesday, November 7th. The company reported $0.11 EPS for the quarter, missing analysts’ consensus estimates of $0.14 by ($0.03). Xponential Fitness had a negative return on equity of 17.66% and a net',
 'a negative return on equity of 17.66% and a net margin of 1.59%. The company had revenue of $80.44 million during the quarter, compared to analysts’ expectations of $74.17 million. During the same period in the prior year, the company posted $0.10 earnings per share. The company’s revenue was up 26.1% on a year-over-year basis. Equities research analysts expect that Xponential Fitness will post 0.25 earnings per share for the current fiscal year. In related news, insider Andrew Hagopian',
 'year. In related news, insider Andrew Hagopian acquired 4,200 shares of the firm’s stock in a transaction dated Wednesday, August 16th. The shares were purchased at an average price of $23.15 per share, with a total value of $97,230.00. Following the completion of the purchase, the insider now directly owns 8,800 shares of the company’s stock, valued at $203,720. The purchase was disclosed in a document filed with the SEC, which can be accessed throughthe SEC website. In other Xponential',
 'throughthe SEC website. In other Xponential Fitness news, CEOAnthony Geislerbought 21,750 shares of the business’s stock in a transaction that occurred on Tuesday, August 15th. The stock was purchased at an average price of $22.93 per share, for a total transaction of $498,727.50. Following the completion of the transaction, the chief executive officer now owns 361,565 shares of the company’s stock, valued at approximately $8,290,685.45. The transaction was disclosed in a legal filing with the',
 'was disclosed in a legal filing with the Securities & Exchange Commission, which is accessible throughthe SEC website. Also, insider Andrew Hagopian bought 4,200 shares of the business’s stock in a transaction that occurred on Wednesday, August 16th. The shares were acquired at an average price of $23.15 per share, with a total value of $97,230.00. Following the transaction, the insider now directly owns 8,800 shares of the company’s stock, valued at approximately $203,720. The disclosure for',
 'at approximately $203,720. The disclosure for this purchase can be foundhere. Insiders have purchased 27,950 shares of company stock valued at $638,508 over the last quarter. 47.86% of the stock is currently owned by company insiders. Several institutional investors have recently made changes to their positions in XPOF. Macquarie Group Ltd. grew its position in shares of Xponential Fitness by 133.2% during the second quarter. Macquarie Group Ltd. now owns 2,696 shares of the company’s stock',
 'Ltd. now owns 2,696 shares of the company’s stock worth $34,000 after purchasing an additional 1,540 shares in the last quarter. Point72 Hong Kong Ltd purchased a new stake in shares of Xponential Fitness during the second quarter worth about $34,000. Ameritas Investment Partners Inc. grew its position in shares of Xponential Fitness by 50.1% during the second quarter. Ameritas Investment Partners Inc. now owns 2,041 shares of the company’s stock worth $35,000 after purchasing an additional 681',
 'worth $35,000 after purchasing an additional 681 shares in the last quarter. Quarry LP purchased a new position in Xponential Fitness during the 2nd quarter valued at approximately $38,000. Finally, Royal Bank of Canada grew its holdings in Xponential Fitness by 48.8% during the 2nd quarter. Royal Bank of Canada now owns 2,906 shares of the company’s stock valued at $50,000 after buying an additional 953 shares in the last quarter. Hedge funds and other institutional investors own 52.97% of the',
 'other institutional investors own 52.97% of the company’s stock. (Get Free Report) Xponential Fitness, Inc, through its subsidiaries, operates as a boutique fitness franchisor in North America. It offers pilates, indoor cycling, barre, stretching, rowing, dancing, boxing, running, functional training, and yoga services under the Club Pilates, Pure Barre, CycleBar, StretchLab, Row House, YogaSix, Rumble, AKT, Stride, and BFT brands.']

#### SemanticChunker

In [73]:
from langchain_experimental.text_splitter import SemanticChunker

text_splitter = SemanticChunker(encoder, breakpoint_threshold_type="percentile", breakpoint_threshold_amount=80, min_chunk_size=50)

docs = text_splitter.create_documents(article)

chunks = [doc.page_content for doc in docs]
chunks

['Title: Xponential Fitness (NYSE:XPOF) Price Target Lowered to $31.00 at Raymond James. Content: Xponential Fitness (NYSE:XPOF–Free Report)had its price target trimmed by Raymond James from $40.00 to $31.00 in a report issued on Wednesday,Benzingareports. The brokerage currently has a strong-buy rating on the stock. XPOF has been the topic of several other reports. Piper Sandler dropped their price objective on Xponential Fitness from $26.00 to $20.00 in a research report on Thursday, October 12th. Stifel Nicolaus initiated coverage on Xponential Fitness in a research report on Friday, October 13th. They set a hold rating and a $18.00 price objective on the stock. Citigroup dropped their price objective on Xponential Fitness from $39.00 to $30.00 in a research report on Friday, August 4th. Guggenheim dropped their price objective on Xponential Fitness from $32.00 to $30.00 and set a buy rating on the stock in a research report on Friday, September 15th. Finally, Bank of America cut Xponential Fitness from a buy rating to a neutral rating and dropped their price objective for the company from $35.00 to $16.00 in a research report on Wednesday, November 1st. Three research analysts have rated the stock with a hold rating, five have given a buy rating and one has assigned a strong buy rating to the company’s stock.',
 'According to data from MarketBeat, the company presently has an average rating of Moderate Buy and an average price target of $27.90. Get Our Latest Stock Report on XPOF Want More Great Investing Ideas?10 Stocks to Sell NOW!3 Stocks to DOUBLE This YearThe 10 Best Stocks to Own in 20237 Stocks to Buy and Hold ForeverShares ofXPOF stockopened at $13.31 on Wednesday. The stock has a market cap of $665.10 million, a price-to-earnings ratio of -5.32, a PEG ratio of 1.13 and a beta of 1.27.',
 'The business’s fifty day moving average is $15.84 and its 200 day moving average is $21.06. Xponential Fitness has a twelve month low of $11.31 and a twelve month high of $33.58. Xponential Fitness (NYSE:XPOF–Get Free Report) last released its earnings results on Tuesday, November 7th. The company reported $0.11 EPS for the quarter, missing analysts’ consensus estimates of $0.14 by ($0.03). Xponential Fitness had a negative return on equity of 17.66% and a net margin of 1.59%. The company had revenue of $80.44 million during the quarter, compared to analysts’ expectations of $74.17 million.',
 'During the same period in the prior year, the company posted $0.10 earnings per share.',
 'The company’s revenue was up 26.1% on a year-over-year basis. Equities research analysts expect that Xponential Fitness will post 0.25 earnings per share for the current fiscal year. In related news, insider Andrew Hagopian acquired 4,200 shares of the firm’s stock in a transaction dated Wednesday, August 16th.',
 'The shares were purchased at an average price of $23.15 per share, with a total value of $97,230.00. Following the completion of the purchase, the insider now directly owns 8,800 shares of the company’s stock, valued at $203,720.',
 'The purchase was disclosed in a document filed with the SEC, which can be accessed throughthe SEC website. In other Xponential Fitness news, CEOAnthony Geislerbought 21,750 shares of the business’s stock in a transaction that occurred on Tuesday, August 15th. The stock was purchased at an average price of $22.93 per share, for a total transaction of $498,727.50.',
 'Following the completion of the transaction, the chief executive officer now owns 361,565 shares of the company’s stock, valued at approximately $8,290,685.45. The transaction was disclosed in a legal filing with the Securities & Exchange Commission, which is accessible throughthe SEC website. Also, insider Andrew Hagopian bought 4,200 shares of the business’s stock in a transaction that occurred on Wednesday, August 16th. The shares were acquired at an average price of $23.15 per share, with a total value of $97,230.00. Following the transaction, the insider now directly owns 8,800 shares of the company’s stock, valued at approximately $203,720. The disclosure for this purchase can be foundhere. Insiders have purchased 27,950 shares of company stock valued at $638,508 over the last quarter. 47.86% of the stock is currently owned by company insiders. Several institutional investors have recently made changes to their positions in XPOF.',
 'Macquarie Group Ltd. grew its position in shares of Xponential Fitness by 133.2% during the second quarter. Macquarie Group Ltd. now owns 2,696 shares of the company’s stock worth $34,000 after purchasing an additional 1,540 shares in the last quarter. Point72 Hong Kong Ltd purchased a new stake in shares of Xponential Fitness during the second quarter worth about $34,000. Ameritas Investment Partners Inc. grew its position in shares of Xponential Fitness by 50.1% during the second quarter. Ameritas Investment Partners Inc. now owns 2,041 shares of the company’s stock worth $35,000 after purchasing an additional 681 shares in the last quarter.',
 'Quarry LP purchased a new position in Xponential Fitness during the 2nd quarter valued at approximately $38,000. Finally, Royal Bank of Canada grew its holdings in Xponential Fitness by 48.8% during the 2nd quarter. Royal Bank of Canada now owns 2,906 shares of the company’s stock valued at $50,000 after buying an additional 953 shares in the last quarter. Hedge funds and other institutional investors own 52.97% of the company’s stock.',
 '(Get Free Report) Xponential Fitness, Inc, through its subsidiaries, operates as a boutique fitness franchisor in North America. It offers pilates, indoor cycling, barre, stretching, rowing, dancing, boxing, running, functional training, and yoga services under the Club Pilates, Pure Barre, CycleBar, StretchLab, Row House, YogaSix, Rumble, AKT, Stride, and BFT brands.',
 '']

#### Создание коллекции

In [79]:
from qdrant_client.models import Distance, VectorParams

strategies = [
	{"name": "recursive_character", "chunk_size": [300, 400, 450, 500]},        # "chunk_overlap": [30, 40, 45, 50]
	{"name": "semantic", "breakpoint_threshold_amount": [70, 80, 85, 90, 95]}   #  "breakpoint_threshold_type": ["percentile"], "min_chunk_size": [100]
]

# Создание коллекции
collection_name = "semantic_search"


def get_collections_names(strategies):

    result = []

    for strategy in strategies:
        name = strategy["name"]

        if name == "recursive_character":
            for chunk_size in strategy["chunk_size"]:
                vector_name = f"{name}_{chunk_size}"
                result.append(vector_name)
            
        if name == "semantic":
            for breakpoint_threshold_amount in strategy["breakpoint_threshold_amount"]:
                vector_name = f"{name}_{breakpoint_threshold_amount}"
                result.append(vector_name)

    return result


if client.collection_exists(collection_name=collection_name):
    client.delete_collection(collection_name=collection_name)

vectors_config = {}

for vector_name in get_collections_names(strategies):

    vectors_config[vector_name] = models.VectorParams(
            size=768, 
            distance=models.Distance.COSINE
            )


client.create_collection(
    collection_name=collection_name,
    vectors_config=vectors_config
)

client.create_payload_index(
    collection_name=collection_name,
    field_name="title",
    field_schema=models.PayloadSchemaType.KEYWORD,
)

client.create_payload_index(
    collection_name=collection_name,
    field_name="url",
    field_schema=models.PayloadSchemaType.KEYWORD,
)

UpdateResult(operation_id=4, status=<UpdateStatus.COMPLETED: 'completed'>)

#### Загрузка данных

In [12]:
def recursive_character_splitter(text, chunk_size):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_size * 0.1,
    )

    docs = text_splitter.create_documents(article)
    return [doc.page_content for doc in docs]

def semantic_splitter(text, threshold):
    text_splitter = SemanticChunker(
        encoder,
        breakpoint_threshold_type="percentile",
        breakpoint_threshold_amount=threshold,
        min_chunk_size=50)

    docs = text_splitter.create_documents(article)

    return [doc.page_content for doc in docs]

In [ ]:
from tqdm.auto import tqdm

idx = 0
points = []


for news in tqdm(samples.to_dict('records'), desc="Processing news"):

    for chunk in recursive_character_splitter(news["full_content"], chunk_size=300):
        points.append(models.PointStruct(
            id=idx,
            vector={"recursive_character_300": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
        idx += 1

    for chunk in recursive_character_splitter(news["full_content"], chunk_size=400):
        points.append(models.PointStruct(
            id=idx,
            vector={"recursive_character_400": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
        idx += 1

    for chunk in recursive_character_splitter(news["full_content"], chunk_size=450):
        points.append(models.PointStruct(
            id=idx,
            vector={"recursive_character_450": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
        idx += 1

    for chunk in recursive_character_splitter(news["full_content"], chunk_size=500):
        points.append(models.PointStruct(
            id=idx,
            vector={"recursive_character_500": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
        idx += 1

    for chunk in semantic_splitter(news["full_content"], threshold=70):
        points.append(models.PointStruct(
            id=idx,
            vector={"semantic_70": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
        idx += 1

    for chunk in semantic_splitter(news["full_content"], threshold=80):
        points.append(models.PointStruct(
            id=idx,
            vector={"semantic_80": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
    idx += 1

    for chunk in semantic_splitter(news["full_content"], threshold=85):
        points.append(models.PointStruct(
            id=idx,
            vector={"semantic_85": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
    idx += 1

    for chunk in semantic_splitter(news["full_content"], threshold=90):
        points.append(models.PointStruct(
            id=idx,
            vector={"semantic_90": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
    idx += 1

    for chunk in semantic_splitter(news["full_content"], threshold=95):
        points.append(models.PointStruct(
            id=idx,
            vector={"semantic_95": encoder.embed_query(f"passage: {chunk}")},
            payload={
                "title": news["title"], 
                "url": news["url"],
                # "chunk": chunk
            }
        ))
    idx += 1
		
client.upload_points(collection_name='semantic_search', points=points)
print(f"Uploaded {idx} vectors across three chunking strategies")

Processing news:   0%|          | 0/1500 [00:00<?, ?it/s]

Uploaded 132000 vectors across three chunking strategies

#### Оценка качества поиска

In [ ]:
def search_and_compare(query, strategies, k=3):
    """Compare search results across all three chunking strategies"""
    print(f"Query: '{query}'\n")
    
    for strategy in strategies:
        results = client.query_points(
            collection_name='semantic_search',
            query=encoder.embed_query(query),
            using=strategy,
            limit=k,
        )
        
        print(f"--- {strategy.upper()} CHUNKING ---")
        for i, point in enumerate(results.points, 1):
            payload = point.payload
            print(f"{i}. Title: {payload['title']} | Score: {point.score:.3f}")
            print(f"   URL: {payload['url']}...")
        print()


collections = get_collections_names(strategies)

search_and_compare("Expected valuation of the global intelligent oximetry industry in the long-term business report", collections, k=10)

Query: 'Expected valuation of the global intelligent oximetry industry in the long-term business report'

--- RECURSIVE_CHARACTER_300 CHUNKING ---
1. Title: Use This Investing Formula To Reach Financial Freedom In Retirement | Score: 0.825
   URL: https://www.forbes.com/sites/bernadettejoy/2023/11/29/use-this-investing-formula-to-reach-financial-freedom-in-retirement/...
2. Title: Hamas violated international law – South Africa | Score: 0.825
   URL: https://www.rt.com/africa/587741-south-africa-condemn-hamas/...
3. Title: Wesco International Reports Third Quarter 2023 Results | Score: 0.825
   URL: https://www.marketscreener.com/quote/stock/WESCO-INTERNATIONAL-INC-14849/news/Wesco-International-Reports-Third-Quarter-2023-Results-45221006/...
4. Title: Air India gets notice over facilities for passengers | Score: 0.825
   URL: https://timesofindia.indiatimes.com/india/air-india-gets-notice-over-facilities-for-passengers/articleshow/105052982.cms...
5. Title: Govt grants approvals to 27 firms under new IT hardware PLI scheme | Score: 0.825
   URL: https://economictimes.indiatimes.com/tech/technology/pli-scheme-govt-grants-approvals-to-27-firms/articleshow/105314073.cms...
6. Title: Earnest Partners LLC Has $14.92 Million Holdings in Elevance Health, Inc. (NYSE:ELV) | Score: 0.825
   URL: https://www.etfdailynews.com/2023/11/07/earnest-partners-llc-has-14-92-million-holdings-in-elevance-health-inc-nyseelv/...
7. Title: Visionary Wealth Advisors Lowers Position in Costco Wholesale Co. (NASDAQ:COST) | Score: 0.825
   URL: https://www.etfdailynews.com/2023/11/27/visionary-wealth-advisors-lowers-position-in-costco-wholesale-co-nasdaqcost/...
8. Title: Fiji minister urges 'quicker' plastic pollution treaty | Score: 0.825
   URL: https://phys.org/news/2023-10-fiji-minister-urges-quicker-plastic.html...
9. Title: BGHL (GBP): NAV(s) | Score: 0.825
   URL: https://www.globenewswire.com/news-release/2023/10/18/2762035/0/en/BGHL-GBP-NAV-s.html...
10. Title: Smart Pulse Oximeters Market Size to Reach USD 2.3 billion by 2031 at 4.6% CAGR | Report by Transparency Market Research Inc. | Score: 0.825
   URL: https://www.globenewswire.com/news-release/2023/11/07/2774725/32656/en/Smart-Pulse-Oximeters-Market-Size-to-Reach-USD-2-3-billion-by-2031-at-4-6-CAGR-Report-by-Transparency-Market-Research-Inc.html...

--- RECURSIVE_CHARACTER_400 CHUNKING ---
1. Title: Change in the Board of Anoto | Score: 0.795
   URL: https://www.globenewswire.com/news-release/2023/11/02/2771908/0/en/Change-in-the-Board-of-Anoto.html...
2. Title: ContraFect (NASDAQ:CFRX) Research Coverage Started at StockNews.com | Score: 0.795
   URL: https://www.etfdailynews.com/2023/11/15/contrafect-nasdaqcfrx-research-coverage-started-at-stocknews-com/...
3. Title: King Luther Capital Management Corp Acquires 1,629 Shares of Paylocity Holding Co. (NASDAQ:PCTY) | Score: 0.795
   URL: https://www.etfdailynews.com/2023/11/23/king-luther-capital-management-corp-acquires-1629-shares-of-paylocity-holding-co-nasdaqpcty/...
4. Title: abrdn plc Trims Stock Holdings in CSX Co. (NASDAQ:CSX) | Score: 0.795
   URL: https://www.etfdailynews.com/2023/11/04/abrdn-plc-trims-stock-holdings-in-csx-co-nasdaqcsx/...
5. Title: Breaking Down the Ending of Netflix’s New Swedish Thriller A Nearly Normal Family | Score: 0.795
   URL: https://time.com/6338421/a-nearly-normal-family-netflix-ending-explained/...
6. Title: Roth Mkm Reiterates “Buy” Rating for Progressive (NYSE:PGR) | Score: 0.795
   URL: https://www.etfdailynews.com/2023/11/24/roth-mkm-reiterates-buy-rating-for-progressive-nysepgr/...
7. Title: Xponential Fitness (NYSE:XPOF) Price Target Lowered to $31.00 at Raymond James | Score: 0.795
   URL: https://www.etfdailynews.com/2023/11/12/xponential-fitness-nysexpof-price-target-lowered-to-31-00-at-raymond-james/...
8. Title: COVID:11 US states register 10% increase in coronavirus hospitalizations. Everything you should know about it | Score: 0.795
   URL: https://economictimes.indiatimes.com/news/international/us/covid11-us-states-register-10-increase-in-coronavirus-hospitalizations-everything-you-should-know-about-it/articleshow/105593817.cms...
9. Title: Edgestream Partners L.P. Invests $1.46 Million in Bank of America Co. (NYSE:BAC) | Score: 0.795
   URL: https://www.etfdailynews.com/2023/11/21/edgestream-partners-l-p-invests-1-46-million-in-bank-of-america-co-nysebac/...
10. Title: Toast, Inc. (NYSE:TOST) Insider Stephen Fredette Sells 966 Shares | Score: 0.795
   URL: https://www.etfdailynews.com/2023/11/04/toast-inc-nysetost-insider-stephen-fredette-sells-966-shares/...

--- RECURSIVE_CHARACTER_450 CHUNKING ---
1. Title: Change in the Board of Anoto | Score: 0.797
   URL: https://www.globenewswire.com/news-release/2023/11/02/2771908/0/en/Change-in-the-Board-of-Anoto.html...
2. Title: ContraFect (NASDAQ:CFRX) Research Coverage Started at StockNews.com | Score: 0.797
   URL: https://www.etfdailynews.com/2023/11/15/contrafect-nasdaqcfrx-research-coverage-started-at-stocknews-com/...
3. Title: Emerson Electric Co. (NYSE:EMR) Holdings Raised by Trust Co of Kansas | Score: 0.797
   URL: https://www.etfdailynews.com/2023/11/02/emerson-electric-co-nyseemr-holdings-raised-by-trust-co-of-kansas/...
4. Title: King Luther Capital Management Corp Acquires 1,629 Shares of Paylocity Holding Co. (NASDAQ:PCTY) | Score: 0.797
   URL: https://www.etfdailynews.com/2023/11/23/king-luther-capital-management-corp-acquires-1629-shares-of-paylocity-holding-co-nasdaqpcty/...
5. Title: Insider Selling: Delek Logistics Partners, LP (NYSE:DKL) CFO Sells $17,059.00 in Stock | Score: 0.797
   URL: https://www.etfdailynews.com/2023/11/16/insider-selling-delek-logistics-partners-lp-nysedkl-cfo-sells-17059-00-in-stock/...
6. Title: abrdn plc Trims Stock Holdings in CSX Co. (NASDAQ:CSX) | Score: 0.797
   URL: https://www.etfdailynews.com/2023/11/04/abrdn-plc-trims-stock-holdings-in-csx-co-nasdaqcsx/...
7. Title: Breaking Down the Ending of Netflix’s New Swedish Thriller A Nearly Normal Family | Score: 0.797
   URL: https://time.com/6338421/a-nearly-normal-family-netflix-ending-explained/...
8. Title: The Highly Anticipated Idaho Outdoor Fieldhouse Marks a New Era in Sports and Recreation, Revolutionizing Accessible Recreation for Veterans and Athletes with Physical Disabilities | Score: 0.797
   URL: https://www.globenewswire.com/news-release/2023/11/13/2779180/0/en/The-Highly-Anticipated-Idaho-Outdoor-Fieldhouse-Marks-a-New-Era-in-Sports-and-Recreation-Revolutionizing-Accessible-Recreation-for-Veterans-and-Athletes-with-Physical-Disabilities.html...
9. Title: COVID:11 US states register 10% increase in coronavirus hospitalizations. Everything you should know about it | Score: 0.797
   URL: https://economictimes.indiatimes.com/news/international/us/covid11-us-states-register-10-increase-in-coronavirus-hospitalizations-everything-you-should-know-about-it/articleshow/105593817.cms...
10. Title: Toast, Inc. (NYSE:TOST) Insider Stephen Fredette Sells 966 Shares | Score: 0.797
   URL: https://www.etfdailynews.com/2023/11/04/toast-inc-nysetost-insider-stephen-fredette-sells-966-shares/...

--- RECURSIVE_CHARACTER_500 CHUNKING ---
1. Title: Insider Selling: Delek Logistics Partners, LP (NYSE:DKL) CFO Sells $17,059.00 in Stock | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/16/insider-selling-delek-logistics-partners-lp-nysedkl-cfo-sells-17059-00-in-stock/...
2. Title: Pinterest, Inc. (NYSE:PINS) Shares Bought by State Board of Administration of Florida Retirement System | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/29/pinterest-inc-nysepins-shares-bought-by-state-board-of-administration-of-florida-retirement-system/...
3. Title: abrdn plc Trims Stock Holdings in CSX Co. (NASDAQ:CSX) | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/04/abrdn-plc-trims-stock-holdings-in-csx-co-nasdaqcsx/...
4. Title: Change in the Board of Anoto | Score: 0.793
   URL: https://www.globenewswire.com/news-release/2023/11/02/2771908/0/en/Change-in-the-Board-of-Anoto.html...
5. Title: King Luther Capital Management Corp Acquires 1,629 Shares of Paylocity Holding Co. (NASDAQ:PCTY) | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/23/king-luther-capital-management-corp-acquires-1629-shares-of-paylocity-holding-co-nasdaqpcty/...
6. Title: Emerson Electric Co. (NYSE:EMR) Holdings Raised by Trust Co of Kansas | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/02/emerson-electric-co-nyseemr-holdings-raised-by-trust-co-of-kansas/...
7. Title: Toast, Inc. (NYSE:TOST) Insider Stephen Fredette Sells 966 Shares | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/04/toast-inc-nysetost-insider-stephen-fredette-sells-966-shares/...
8. Title: ContraFect (NASDAQ:CFRX) Research Coverage Started at StockNews.com | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/15/contrafect-nasdaqcfrx-research-coverage-started-at-stocknews-com/...
9. Title: Roth Mkm Reiterates “Buy” Rating for Progressive (NYSE:PGR) | Score: 0.793
   URL: https://www.etfdailynews.com/2023/11/24/roth-mkm-reiterates-buy-rating-for-progressive-nysepgr/...
10. Title: Breaking Down the Ending of Netflix’s New Swedish Thriller A Nearly Normal Family | Score: 0.793
   URL: https://time.com/6338421/a-nearly-normal-family-netflix-ending-explained/...

--- SEMANTIC_70 CHUNKING ---
1. Title: Global-e Online (NASDAQ:GLBE) Shares Up 8% | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/20/global-e-online-nasdaqglbe-shares-up-8/...
2. Title: Beck Bode LLC Makes New Investment in STMicroelectronics (NYSE:STM) | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/16/beck-bode-llc-makes-new-investment-in-stmicroelectronics-nysestm/...
3. Title: Lumentum (NASDAQ:LITE) PT Lowered to $55.00 | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/04/lumentum-nasdaqlite-pt-lowered-to-55-00/...
4. Title: Israeli airstrike hits main building of Gaza's Al Shifa hospital: Palestinian health official | Score: 0.808
   URL: https://www.globalsecurity.org/military/library/news/2023/11/mil-231113-pdo09.htm...
5. Title: Ice sheet surface melt is accelerating in Greenland and slowing in Antarctica, finds study | Score: 0.808
   URL: https://phys.org/news/2023-10-ice-sheet-surface-greenland-antarctica.html...
6. Title: Energizer (NYSE:ENR) Downgraded to “Sector Perform” at Royal Bank of Canada | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/15/energizer-nyseenr-downgraded-to-sector-perform-at-royal-bank-of-canada/...
7. Title: CMC Metals (CVE:CMB) Trading 8.3% Higher | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/16/cmc-metals-cvecmb-trading-8-3-higher/...
8. Title: Queen Camilla's divorce ultimatum and the Clintons betray Joe Biden, in this week's dubious tabloids | Score: 0.808
   URL: https://boingboing.net/2023/10/07/queen-camillas-divorce-ultimatum-and-the-clintons-betray-joe-biden-in-this-weeks-dubious-tabloids.html...
9. Title: Hubble images NGC 941, a spiral galaxy with an explosive past | Score: 0.808
   URL: https://phys.org/news/2023-11-hubble-images-ngc-spiral-galaxy.html...
10. Title: US House Republicans eye plan to avert government shutdown as Moody's warns | Score: 0.808
   URL: https://economictimes.indiatimes.com/news/international/us/us-house-republicans-eye-plan-to-avert-government-shutdown-as-moodys-warns/articleshow/105149293.cms...

--- SEMANTIC_80 CHUNKING ---
1. Title: ContraFect (NASDAQ:CFRX) Research Coverage Started at StockNews.com | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/15/contrafect-nasdaqcfrx-research-coverage-started-at-stocknews-com/...
2. Title: Emerson Electric Co. (NYSE:EMR) Holdings Raised by Trust Co of Kansas | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/02/emerson-electric-co-nyseemr-holdings-raised-by-trust-co-of-kansas/...
3. Title: King Luther Capital Management Corp Acquires 1,629 Shares of Paylocity Holding Co. (NASDAQ:PCTY) | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/23/king-luther-capital-management-corp-acquires-1629-shares-of-paylocity-holding-co-nasdaqpcty/...
4. Title: Insider Selling: Delek Logistics Partners, LP (NYSE:DKL) CFO Sells $17,059.00 in Stock | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/16/insider-selling-delek-logistics-partners-lp-nysedkl-cfo-sells-17059-00-in-stock/...
5. Title: abrdn plc Trims Stock Holdings in CSX Co. (NASDAQ:CSX) | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/04/abrdn-plc-trims-stock-holdings-in-csx-co-nasdaqcsx/...
6. Title: Pinterest, Inc. (NYSE:PINS) Shares Bought by State Board of Administration of Florida Retirement System | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/29/pinterest-inc-nysepins-shares-bought-by-state-board-of-administration-of-florida-retirement-system/...
7. Title: Breaking Down the Ending of Netflix’s New Swedish Thriller A Nearly Normal Family | Score: 0.808
   URL: https://time.com/6338421/a-nearly-normal-family-netflix-ending-explained/...
8. Title: Roth Mkm Reiterates “Buy” Rating for Progressive (NYSE:PGR) | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/24/roth-mkm-reiterates-buy-rating-for-progressive-nysepgr/...
9. Title: Toast, Inc. (NYSE:TOST) Insider Stephen Fredette Sells 966 Shares | Score: 0.808
   URL: https://www.etfdailynews.com/2023/11/04/toast-inc-nysetost-insider-stephen-fredette-sells-966-shares/...
10. Title: Change in the Board of Anoto | Score: 0.808
   URL: https://www.globenewswire.com/news-release/2023/11/02/2771908/0/en/Change-in-the-Board-of-Anoto.html...

--- SEMANTIC_85 CHUNKING ---
1. Title: ContraFect (NASDAQ:CFRX) Research Coverage Started at StockNews.com | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/15/contrafect-nasdaqcfrx-research-coverage-started-at-stocknews-com/...
2. Title: Emerson Electric Co. (NYSE:EMR) Holdings Raised by Trust Co of Kansas | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/02/emerson-electric-co-nyseemr-holdings-raised-by-trust-co-of-kansas/...
3. Title: King Luther Capital Management Corp Acquires 1,629 Shares of Paylocity Holding Co. (NASDAQ:PCTY) | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/23/king-luther-capital-management-corp-acquires-1629-shares-of-paylocity-holding-co-nasdaqpcty/...
4. Title: Insider Selling: Delek Logistics Partners, LP (NYSE:DKL) CFO Sells $17,059.00 in Stock | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/16/insider-selling-delek-logistics-partners-lp-nysedkl-cfo-sells-17059-00-in-stock/...
5. Title: abrdn plc Trims Stock Holdings in CSX Co. (NASDAQ:CSX) | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/04/abrdn-plc-trims-stock-holdings-in-csx-co-nasdaqcsx/...
6. Title: Pinterest, Inc. (NYSE:PINS) Shares Bought by State Board of Administration of Florida Retirement System | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/29/pinterest-inc-nysepins-shares-bought-by-state-board-of-administration-of-florida-retirement-system/...
7. Title: Breaking Down the Ending of Netflix’s New Swedish Thriller A Nearly Normal Family | Score: 0.763
   URL: https://time.com/6338421/a-nearly-normal-family-netflix-ending-explained/...
8. Title: Roth Mkm Reiterates “Buy” Rating for Progressive (NYSE:PGR) | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/24/roth-mkm-reiterates-buy-rating-for-progressive-nysepgr/...
9. Title: Toast, Inc. (NYSE:TOST) Insider Stephen Fredette Sells 966 Shares | Score: 0.763
   URL: https://www.etfdailynews.com/2023/11/04/toast-inc-nysetost-insider-stephen-fredette-sells-966-shares/...
10. Title: Change in the Board of Anoto | Score: 0.763
   URL: https://www.globenewswire.com/news-release/2023/11/02/2771908/0/en/Change-in-the-Board-of-Anoto.html...

--- SEMANTIC_90 CHUNKING ---
1. Title: ContraFect (NASDAQ:CFRX) Research Coverage Started at StockNews.com | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/15/contrafect-nasdaqcfrx-research-coverage-started-at-stocknews-com/...
2. Title: Emerson Electric Co. (NYSE:EMR) Holdings Raised by Trust Co of Kansas | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/02/emerson-electric-co-nyseemr-holdings-raised-by-trust-co-of-kansas/...
3. Title: King Luther Capital Management Corp Acquires 1,629 Shares of Paylocity Holding Co. (NASDAQ:PCTY) | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/23/king-luther-capital-management-corp-acquires-1629-shares-of-paylocity-holding-co-nasdaqpcty/...
4. Title: Insider Selling: Delek Logistics Partners, LP (NYSE:DKL) CFO Sells $17,059.00 in Stock | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/16/insider-selling-delek-logistics-partners-lp-nysedkl-cfo-sells-17059-00-in-stock/...
5. Title: abrdn plc Trims Stock Holdings in CSX Co. (NASDAQ:CSX) | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/04/abrdn-plc-trims-stock-holdings-in-csx-co-nasdaqcsx/...
6. Title: Pinterest, Inc. (NYSE:PINS) Shares Bought by State Board of Administration of Florida Retirement System | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/29/pinterest-inc-nysepins-shares-bought-by-state-board-of-administration-of-florida-retirement-system/...
7. Title: Breaking Down the Ending of Netflix’s New Swedish Thriller A Nearly Normal Family | Score: 0.773
   URL: https://time.com/6338421/a-nearly-normal-family-netflix-ending-explained/...
8. Title: Roth Mkm Reiterates “Buy” Rating for Progressive (NYSE:PGR) | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/24/roth-mkm-reiterates-buy-rating-for-progressive-nysepgr/...
9. Title: Toast, Inc. (NYSE:TOST) Insider Stephen Fredette Sells 966 Shares | Score: 0.773
   URL: https://www.etfdailynews.com/2023/11/04/toast-inc-nysetost-insider-stephen-fredette-sells-966-shares/...
10. Title: Change in the Board of Anoto | Score: 0.773
   URL: https://www.globenewswire.com/news-release/2023/11/02/2771908/0/en/Change-in-the-Board-of-Anoto.html...

--- SEMANTIC_95 CHUNKING ---
1. Title: ContraFect (NASDAQ:CFRX) Research Coverage Started at StockNews.com | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/15/contrafect-nasdaqcfrx-research-coverage-started-at-stocknews-com/...
2. Title: Emerson Electric Co. (NYSE:EMR) Holdings Raised by Trust Co of Kansas | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/02/emerson-electric-co-nyseemr-holdings-raised-by-trust-co-of-kansas/...
3. Title: King Luther Capital Management Corp Acquires 1,629 Shares of Paylocity Holding Co. (NASDAQ:PCTY) | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/23/king-luther-capital-management-corp-acquires-1629-shares-of-paylocity-holding-co-nasdaqpcty/...
4. Title: Insider Selling: Delek Logistics Partners, LP (NYSE:DKL) CFO Sells $17,059.00 in Stock | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/16/insider-selling-delek-logistics-partners-lp-nysedkl-cfo-sells-17059-00-in-stock/...
5. Title: abrdn plc Trims Stock Holdings in CSX Co. (NASDAQ:CSX) | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/04/abrdn-plc-trims-stock-holdings-in-csx-co-nasdaqcsx/...
6. Title: Pinterest, Inc. (NYSE:PINS) Shares Bought by State Board of Administration of Florida Retirement System | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/29/pinterest-inc-nysepins-shares-bought-by-state-board-of-administration-of-florida-retirement-system/...
7. Title: Breaking Down the Ending of Netflix’s New Swedish Thriller A Nearly Normal Family | Score: 0.781
   URL: https://time.com/6338421/a-nearly-normal-family-netflix-ending-explained/...
8. Title: Roth Mkm Reiterates “Buy” Rating for Progressive (NYSE:PGR) | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/24/roth-mkm-reiterates-buy-rating-for-progressive-nysepgr/...
9. Title: Toast, Inc. (NYSE:TOST) Insider Stephen Fredette Sells 966 Shares | Score: 0.781
   URL: https://www.etfdailynews.com/2023/11/04/toast-inc-nysetost-insider-stephen-fredette-sells-966-shares/...
10. Title: Change in the Board of Anoto | Score: 0.781

Целевая новость: 

Title: Smart Pulse Oximeters Market Size to Reach USD 2.3 billion by 2031 at 4.6% CAGR | Report by Transparency Market Research Inc. | Score: 0.825
URL: https://www.globenewswire.com/news-release/2023/11/07/2774725/32656/en/Smart-Pulse-Oximeters-Market-Size-to-Reach-USD-2-3-billion-by-2031-at-4-6-CAGR-Report-by-Transparency-Market-Research-Inc.html

Абсолютным победителем является стратегия RECURSIVE_CHARACTER_300 - искомая новость в 10 позиции.

In [34]:
client.delete_collection("semantic_search")

True

### HNSW Performance Benchmarking

#### Загрузка данных

Для подбора параметров HNSW возьмём не весь датасет, а стратифицированную выборку из 5 000 статей:

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

dataset = pd.read_parquet("dataset.parquet.gzip")

sample_size = 5000

stratified_sample, _ = train_test_split(
    dataset,
    train_size=(sample_size / len(dataset)),
    stratify=dataset['category'],
    random_state=42
)

stratified_sample

,source_name,title,url,published_at,category,full_content
82201,globalsecurity.org,US secretly pushing Israel to speed up Gaza wa...,https://www.globalsecurity.org/military/librar...,2023-11-14T09:55:34Z,israel,Title: US secretly pushing Israel to speed up ...
65222,etf daily news,"Analysts Set Clearway Energy, Inc. (NYSE:CWEN)...",https://www.etfdailynews.com/2023/11/07/analys...,2023-11-07T10:59:34Z,canada,"Title: Analysts Set Clearway Energy, Inc. (NYS..."
52074,the punch,"Osun to enrol 19,000 retirees in health insura...",https://punchng.com/osun-to-enrol-19000-retire...,2023-11-03T00:15:33Z,health,"Title: Osun to enrol 19,000 retirees in health..."
84679,globenewswire,"Metabolic Testing Market To Reach USD 1,198.4 ...",https://www.globenewswire.com/news-release/202...,2023-11-16T12:10:00Z,technology,Title: Metabolic Testing Market To Reach USD 1...
73424,the times of india,Hundreds of activists demand plastic action in...,https://timesofindia.indiatimes.com/world/rest...,2023-11-11T11:11:16Z,climate,Title: Hundreds of activists demand plastic ac...
...,...,...,...,...,...,...
19506,abc news,Tropical Storm Philippe chugs toward Bermuda o...,https://abcnews.go.com/International/wireStory...,2023-10-05T12:31:50Z,"virgin islands, u.s.",Title: Tropical Storm Philippe chugs toward Be...
103680,etf daily news,"Meritage Group LP Has $233,000 Stock Holdings ...",https://www.etfdailynews.com/2023/11/27/merita...,2023-11-27T18:04:46Z,mexico,"Title: Meritage Group LP Has $233,000 Stock Ho..."
27356,business insider,The mother of tattoo artist Shani Louk who was...,https://www.businessinsider.com/mother-german-...,2023-10-08T11:20:50Z,instagram,Title: The mother of tattoo artist Shani Louk ...
49593,marketscreener.com,Dividend Payment Procedure for shareholders of...,https://www.marketscreener.com/quote/stock/AB-...,2023-10-27T11:03:01Z,lithuania,Title: Dividend Payment Procedure for sharehol...
83679,globenewswire,Sienna Announces November Dividend,https://www.globenewswire.com/news-release/202...,2023-11-15T13:30:00Z,canada,Title: Sienna Announces November Dividend. Con...

#### Создание коллекций и подготовка данных

Создадим коллекции для подбора опитмальных параметров HNSW:

In [ ]:
def create_collection(client, collection_name: str, m: int, ef_construct: int) -> None:
    if client.collection_exists(collection_name=collection_name):
        client.delete_collection(collection_name=collection_name)

    client.create_collection(
        collection_name=collection_name,
        vectors_config=models.VectorParams(size=768, distance=models.Distance.COSINE),
        hnsw_config=models.HnswConfigDiff(
            m=m,
            ef_construct=ef_construct,
            full_scan_threshold=10,
        ),
        optimizers_config=models.OptimizersConfigDiff(
            indexing_threshold=10
        ),
    )
    print(f"Created collection: {collection_name}")


# Test configurations
configs = [
    {"name": "fast_initial_upload", "m": 0, "ef_construct": 100},
    {"name": "memory_optimized", "m": 8, "ef_construct": 100},
    {"name": "balanced", "m": 16, "ef_construct": 200},
    {"name": "high_quality", "m": 32, "ef_construct": 400},
]

for config in configs:
    create_collection(
        client,
        collection_name=f"my_domain_{config['name']}",
        m=config["m"],
        ef_construct=config["ef_construct"],
    )

Created collection: my_domain_fast_initial_upload
Created collection: my_domain_memory_optimized
Created collection: my_domain_balanced
Created collection: my_domain_high_quality

Подготовка всех данных для загрузки:

In [ ]:
from langchain_text_splitters import RecursiveCharacterTextSplitter


text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=300,
        chunk_overlap=30,
    )

def dataset_stream(df, splitter, gpu_batch_size=64):
    meta_cols = ["source_name", "title", "url", "published_at", "category"]
    
    batch_texts = []
    batch_payloads = []
    
    for row in df.itertuples(index=False):
        # Базовые метаданные текущей строки
        payload_base = {col: getattr(row, col) for col in meta_cols}
        
        # Режем текст переданным сплиттером
        chunks = splitter.split_text(str(row.full_content))
        
        for chunk in chunks:
            batch_texts.append(f"passage: {chunk}")
            # Добавляем сам чанк в метаданные, чтобы видеть его при поиске
            current_payload = payload_base.copy()
            current_payload["text"] = chunk
            batch_payloads.append(current_payload)
            
            # Если набрали батч для GPU — кодируем и отдаем
            if len(batch_texts) == gpu_batch_size:
                vectors = encoder.encode(batch_texts, convert_to_numpy=True)
                for v, p in zip(vectors, batch_payloads):
                    yield v, p
                batch_texts, batch_payloads = [], []
                
    # Sending the remaining items
    if batch_texts:
        vectors = encoder.encode(batch_texts, convert_to_numpy=True)
        for v, p in zip(vectors, batch_payloads):
            yield v, p

dataset_streamer = dataset_stream(stratified_sample, text_splitter, gpu_batch_size=128)

all_vectors, all_payloads = zip(*dataset_streamer)

#### Загрузка данных и измерениие времени

In [22]:
import time
import pandas as pd
from qdrant_client import models

def upload_with_timing(collection_name, vectors, payloads, config_name):
    # Warmup — прогрев перед замером
    if len(vectors) > 0:
        client.query_points(collection_name=collection_name, query=vectors[0], limit=1)

    # Используем perf_counter для точности
    start_time = time.perf_counter()

    client.upload_collection(
        collection_name=collection_name,
        vectors=vectors,
        payload=payloads,
        ids=None,
        batch_size=1000,
        parallel=1,
        wait=True
    )

    duration = time.perf_counter() - start_time
    print(f"{config_name}: Uploaded {len(vectors)} points in {duration:.4f}s")
    return duration

def wait_for_indexing_silent(collection_name, timeout=600):
    start_time = time.perf_counter()
    while time.perf_counter() - start_time < timeout:
        info = client.get_collection(collection_name=collection_name)
        if info.status == models.CollectionStatus.GREEN:
            return
        time.sleep(1)
    raise Exception(f"Таймаут индексации: {collection_name}")


results_list = []

for config in configs:
    name = config["name"]
    col_name = f"my_domain_{name}"
    
    duration = upload_with_timing(col_name, all_vectors, all_payloads, name)
    
    results_list.append({
        "config_name": name,
        "points_count": len(all_vectors),
        "upload_time_sec": round(duration, 4),
        "points_per_second": round(len(all_vectors) / duration, 2)
    })

    # Ожидание HNSW
    if config.get("m", 0) > 0:
        wait_for_indexing_silent(col_name)

# Превращаем результаты в DataFrame
df_results = pd.DataFrame(results_list)

print(df_results.to_string(index=False))

fast_initial_upload: Uploaded 115693 points in 19.6421s
memory_optimized: Uploaded 115693 points in 19.4942s
balanced: Uploaded 115693 points in 20.3018s
high_quality: Uploaded 115693 points in 19.0027s
        config_name  points_count  upload_time_sec  points_per_second
fast_initial_upload        115693          19.6421            5890.07
   memory_optimized        115693          19.4942            5934.73
           balanced        115693          20.3018            5698.65
       high_quality        115693          19.0027            6088.23

In [23]:
df_results

           config_name  points_count  upload_time_sec  points_per_second
0  fast_initial_upload        115693          19.6421            5890.07
1     memory_optimized        115693          19.4942            5934.73
2             balanced        115693          20.3018            5698.65
3         high_quality        115693          19.0027            6088.23

#### Benchmark Search Performance

Test search speed with different hnsw_ef values:

In [ ]:
import numpy as np

def benchmark_search(collection_name, query_embedding, query_count=100, ef_values=[64, 128, 256]):

    # Warmup
    client.query_points(collection_name=collection_name, query=query_embedding, limit=1)

    # hnsw_ef: higher = better recall, but slower. Tune per your latency goal.
    results = {}
    for hnsw_ef in ef_values:
        times = []

        # Run multiple queries for more reliable timing
        for _ in range(25):
            start_time = time.time()

            _ = client.query_points(
                collection_name=collection_name,
                query=query_embedding,
                limit=10,
                search_params=models.SearchParams(hnsw_ef=hnsw_ef),
                with_payload=False,
            )

            times.append((time.time() - start_time) * 1000)

        results[hnsw_ef] = {
            "avg_time": np.mean(times),
            "min_time": np.min(times),
            "max_time": np.max(times),
        }

    return results


test_query = "Smart Pulse Oximeters Market Size to Reach USD 2.3 billion by 2031 at 4.6% CAGR"
query_embedding = encoder.encode(test_query)

performance_results = {}
for config in configs:
    if config["m"] > 0:  # Skip m=0 collections for search
        collection_name = f"my_domain_{config['name']}"
        performance_results[config["name"]] = benchmark_search(
            collection_name, query_embedding
        )

performance_results

,memory_optimized,balanced,high_quality
64,"{'avg_time': 1.1963272094726562, 'min_time': 0...","{'avg_time': 1.2056446075439453, 'min_time': 1...","{'avg_time': 1.3165760040283203, 'min_time': 1..."
128,"{'avg_time': 1.335763931274414, 'min_time': 1....","{'avg_time': 1.327981948852539, 'min_time': 1....","{'avg_time': 1.5747451782226562, 'min_time': 1..."
256,"{'avg_time': 1.5015506744384766, 'min_time': 1...","{'avg_time': 1.9254207611083984, 'min_time': 1...","{'avg_time': 2.4020004272460938, 'min_time': 1..."

In [1]:
test_query = "Smart Pulse Oximeters Market Size to Reach USD 2.3 billion by 2031 at 4.6% CAGR"
query_embedding = encoder.encode(test_query)

query_embedding

NameError: name 'encoder' is not defined

# Черновики

РАБОЧИЙ ВАРИАНТ!!! Быстрый вариант загрузки данных в коллекцию c использование сплиттера с параметрами:

In [ ]:
from langchain_text_splitters import RecursiveCharacterTextSplitter


text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=300,
        chunk_overlap=30,
    )

def dataset_stream(df, splitter, gpu_batch_size=64):
    meta_cols = ["source_name", "title", "url", "published_at", "category"]
    
    batch_texts = []
    batch_payloads = []
    
    for row in df.itertuples(index=False):
        # Базовые метаданные текущей строки
        payload_base = {col: getattr(row, col) for col in meta_cols}
        
        # Режем текст переданным сплиттером
        chunks = splitter.split_text(str(row.full_content))
        
        for chunk in chunks:
            batch_texts.append(f"passage: {chunk}")
            # Добавляем сам чанк в метаданные, чтобы видеть его при поиске
            current_payload = payload_base.copy()
            current_payload["text"] = chunk
            batch_payloads.append(current_payload)
            
            # Если набрали батч для GPU — кодируем и отдаем
            if len(batch_texts) == gpu_batch_size:
                vectors = encoder.encode(batch_texts, convert_to_numpy=True)
                for v, p in zip(vectors, batch_payloads):
                    yield v, p
                batch_texts, batch_payloads = [], []
                
    # Доотправляем остатки
    if batch_texts:
        vectors = encoder.encode(batch_texts, convert_to_numpy=True)
        for v, p in zip(vectors, batch_payloads):
            yield v, p

dataset_streamer = dataset_stream(stratified_sample, text_splitter, gpu_batch_size=128)

client.upload_collection(
    collection_name=collection_name,
    vectors=(item[0] for item in dataset_streamer),
    payload=(item[1] for item in dataset_streamer),
    ids=None,
    batch_size=1000,
    parallel=1, # Only 1 GPU...
)

Загрузим и подготовим датасет:

In [ ]:
import pandas as pd
from tqdm.auto import tqdm
from langchain_text_splitters import RecursiveCharacterTextSplitter

tqdm.pandas()


def split_text(text):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=300,
        chunk_overlap=30,
    )
    return splitter.split_text(text)




dataset['full_content'] = dataset['full_content'].progress_apply(split_text)

dataset = dataset.explode('full_content').reset_index(drop=True)

dataset

  0%|          | 0/54834 [00:00<?, ?it/s]

,source_name,title,url,published_at,category,full_content
0,international business times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,nepal,Title: UN Chief Urges World To 'Stop The Madne...
1,international business times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,nepal,"the devastating impact of the phenomenon. ""The..."
2,international business times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,nepal,-- the ones here in the Himalayas supply fresh...
3,international business times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,nepal,Nepal. Glaciers in the wider Himalayan and Hin...
4,international business times,UN Chief Urges World To 'Stop The Madness' Of ...,https://www.ibtimes.com/un-chief-urges-world-s...,2023-10-30T10:12:35Z,nepal,"of the world's most important river systems, i..."
...,...,...,...,...,...,...
1259080,forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,home,your property will appeal to. With plenty of l...
1259081,forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,home,"the locations, markets and available services ..."
1259082,forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,home,and your rates need to be competitive for your...
1259083,forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,home,"pay rent, make requests and communicate. If yo..."
1259084,forbes,Tips For Investing In Short-Term Rentals In Dubai,https://www.forbes.com/sites/forbesbusinesscou...,2023-11-29T14:00:00Z,home,"here is not investment, tax, or financial advi..."

In [ ]:
from sentence_transformers import SentenceTransformer

batch = dataset[:10]["full_content"].to_list()

encoder = SentenceTransformer("intfloat/multilingual-e5-base", device="cuda")

embeddings = encoder.encode(batch)

print(embeddings.shape)

In [243]:
def product_of_odds(data):   # data - список целых чисел
    result = 1
    for i in data:
        if i % 2 == 1:
            result *= i

    return result

print(product_of_odds([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

945